-- AI Course Q&A Schema Migration
-- 1. Add syllabus fields to courses table
ALTER TABLE courses ADD COLUMN IF NOT EXISTS learning_objectives TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS grading_criteria TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS topics JSONB DEFAULT '[]'::jsonb;

-- 2. Create Chat Sessions table for Q&A conversational memory
CREATE TABLE IF NOT EXISTS chat_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id BIGINT REFERENCES student_users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create Chat Messages table to store the dialog history
CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    sender VARCHAR(10) NOT NULL, -- 'STUDENT' or 'AI'
    content TEXT NOT NULL,
    sources JSONB DEFAULT '[]'::jsonb, -- Array of source links cited by AI
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for fast session retrieval
CREATE INDEX IF NOT EXISTS idx_chat_messages_session_id ON chat_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_chat_sessions_student_id ON chat_sessions(student_id);
