-- ================================================================
-- V005: Fix Subject QA schema + populate tech_stacks data
-- 
-- This migration:
--   1. Ensures chat_sessions + chat_messages tables exist (V003)
--   2. Adds syllabus fields to courses if missing
--   3. Populates tech_stacks + repo_tech_stacks from existing repos
-- ================================================================

-- ================================================================
-- PART 1: AI Subject QA Schema (from V003)
-- ================================================================

-- Add syllabus fields to courses table (idempotent)
ALTER TABLE courses ADD COLUMN IF NOT EXISTS learning_objectives TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS grading_criteria TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS topics JSONB DEFAULT '[]'::jsonb;

-- Create Chat Sessions table for Q&A conversational memory
CREATE TABLE IF NOT EXISTS chat_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id BIGINT REFERENCES student_users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create Chat Messages table to store the dialog history
CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    sender VARCHAR(10) NOT NULL,
    content TEXT NOT NULL,
    sources JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for fast session retrieval
CREATE INDEX IF NOT EXISTS idx_chat_messages_session_id ON chat_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_chat_sessions_student_id ON chat_sessions(student_id);

-- ================================================================
-- PART 2: Populate tech_stacks + repo_tech_stacks
-- ================================================================

-- Insert distinct primary_language values as tech stacks
INSERT INTO tech_stacks (name)
SELECT DISTINCT TRIM(primary_language)
FROM github_repos
WHERE primary_language IS NOT NULL
  AND TRIM(primary_language) != ''
  AND NOT EXISTS (SELECT 1 FROM tech_stacks t WHERE LOWER(t.name) = LOWER(TRIM(github_repos.primary_language)))
ON CONFLICT (name) DO NOTHING;

-- Link repos to their primary_language tech stacks
INSERT INTO repo_tech_stacks (repo_id, tech_stack_id)
SELECT r.id, t.id
FROM github_repos r
JOIN tech_stacks t ON LOWER(t.name) = LOWER(TRIM(r.primary_language))
WHERE r.primary_language IS NOT NULL
  AND TRIM(r.primary_language) != ''
  AND NOT EXISTS (
      SELECT 1 FROM repo_tech_stacks rts
      WHERE rts.repo_id = r.id AND rts.tech_stack_id = t.id
  )
ON CONFLICT (repo_id, tech_stack_id) DO NOTHING;

-- Also migrate old tech_stack (singular) column if any repos have it
INSERT INTO tech_stacks (name)
SELECT DISTINCT TRIM(tech_stack)
FROM github_repos
WHERE tech_stack IS NOT NULL
  AND TRIM(tech_stack) != ''
  AND NOT EXISTS (SELECT 1 FROM tech_stacks t WHERE LOWER(t.name) = LOWER(TRIM(github_repos.tech_stack)))
ON CONFLICT (name) DO NOTHING;

INSERT INTO repo_tech_stacks (repo_id, tech_stack_id)
SELECT r.id, t.id
FROM github_repos r
JOIN tech_stacks t ON LOWER(t.name) = LOWER(TRIM(r.tech_stack))
WHERE r.tech_stack IS NOT NULL
  AND TRIM(r.tech_stack) != ''
  AND NOT EXISTS (
      SELECT 1 FROM repo_tech_stacks rts
      WHERE rts.repo_id = r.id AND rts.tech_stack_id = t.id
  )
ON CONFLICT (repo_id, tech_stack_id) DO NOTHING;
