-- ================================================================
-- V006: Community chat, repository socials, and course reviews
-- ================================================================

CREATE TABLE IF NOT EXISTS chat_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    reference_id VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS community_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT NOT NULL REFERENCES chat_channels(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES student_users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS repo_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id BIGINT NOT NULL REFERENCES github_repos(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES student_users(id) ON DELETE CASCADE,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT uk_repo_review_student UNIQUE (repo_id, student_id)
);

CREATE TABLE IF NOT EXISTS repo_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id BIGINT NOT NULL REFERENCES github_repos(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES student_users(id) ON DELETE CASCADE,
    vote_value INTEGER NOT NULL CHECK (vote_value = 1 OR vote_value = -1),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT uk_repo_vote_student UNIQUE (repo_id, student_id)
);

CREATE TABLE IF NOT EXISTS course_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES courses(stt) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES student_users(id) ON DELETE CASCADE,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT uk_course_review_student UNIQUE (course_id, student_id)
);

CREATE INDEX IF NOT EXISTS idx_community_messages_channel ON community_messages(channel_id);
CREATE INDEX IF NOT EXISTS idx_community_messages_student ON community_messages(student_id);
CREATE INDEX IF NOT EXISTS idx_repo_reviews_repo ON repo_reviews(repo_id);
CREATE INDEX IF NOT EXISTS idx_repo_reviews_student ON repo_reviews(student_id);
CREATE INDEX IF NOT EXISTS idx_repo_votes_repo ON repo_votes(repo_id);
CREATE INDEX IF NOT EXISTS idx_repo_votes_student ON repo_votes(student_id);
CREATE INDEX IF NOT EXISTS idx_course_reviews_course ON course_reviews(course_id);
CREATE INDEX IF NOT EXISTS idx_course_reviews_student ON course_reviews(student_id);
