CREATE TABLE IF NOT EXISTS notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(30)  NOT NULL,
    message     VARCHAR(255) NOT NULL,
    target_url  VARCHAR(255),
    is_read     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications (is_read, created_at DESC);
