SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA IF NOT EXISTS "extensions";

CREATE EXTENSION IF NOT EXISTS "vector" WITH SCHEMA "extensions";


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE TYPE "public"."bookmark_target_type" AS ENUM (
    'COURSE',
    'REPO'
);


ALTER TYPE "public"."bookmark_target_type" OWNER TO "postgres";


CREATE TYPE "public"."course_relation_type" AS ENUM (
    'PREREQUISITE',
    'COMPLEMENTARY',
    'COREQUISITE'
);


ALTER TYPE "public"."course_relation_type" OWNER TO "postgres";


CREATE TYPE "public"."note_target_type" AS ENUM (
    'COURSE',
    'REPO',
    'NONE'
);


ALTER TYPE "public"."note_target_type" OWNER TO "postgres";


CREATE TYPE "public"."repo_candidate_status" AS ENUM (
    'NEW',
    'APPROVED',
    'REJECTED'
);


ALTER TYPE "public"."repo_candidate_status" OWNER TO "postgres";


CREATE TYPE "public"."roadmap_item_target_type" AS ENUM (
    'COURSE',
    'REPO'
);


ALTER TYPE "public"."roadmap_item_target_type" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."rls_auto_enable"() RETURNS "event_trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$$;


ALTER FUNCTION "public"."rls_auto_enable"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."admin_users" (
    "id" bigint NOT NULL,
    "username" character varying(255) NOT NULL,
    "password_hash" character varying(255) NOT NULL,
    "active" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."admin_users" OWNER TO "postgres";


ALTER TABLE "public"."admin_users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."admin_users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."chat_channels" (
    "id" bigint NOT NULL,
    "channel_id" character varying(100) NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "name" character varying(255) NOT NULL,
    "reference_id" character varying(50),
    "type" character varying(50) NOT NULL,
    "active" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."chat_channels" OWNER TO "postgres";


ALTER TABLE "public"."chat_channels" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."chat_channels_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."chat_messages" (
    "id" bigint NOT NULL,
    "content" "text" NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "sender" character varying(10) NOT NULL,
    "sources" "jsonb",
    "session_id" "uuid" NOT NULL
);


ALTER TABLE "public"."chat_messages" OWNER TO "postgres";


ALTER TABLE "public"."chat_messages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."chat_messages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."chat_sessions" (
    "id" "uuid" NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "title" character varying(255) NOT NULL,
    "updated_at" timestamp(6) without time zone NOT NULL,
    "student_id" bigint
);


ALTER TABLE "public"."chat_sessions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."community_messages" (
    "id" bigint NOT NULL,
    "content" "text" NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "channel_id" bigint NOT NULL,
    "student_id" bigint NOT NULL,
    "parent_id" bigint
);


ALTER TABLE "public"."community_messages" OWNER TO "postgres";


ALTER TABLE "public"."community_messages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."community_messages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."course_articles" (
    "id" bigint NOT NULL,
    "course_id" bigint NOT NULL,
    "title" character varying(255) NOT NULL,
    "url" character varying(255) NOT NULL,
    "author" character varying(255),
    "description" "text",
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."course_articles" OWNER TO "postgres";


ALTER TABLE "public"."course_articles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."course_articles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."course_assessments" (
    "id" "uuid" NOT NULL,
    "component_code" character varying(50) NOT NULL,
    "course_code" character varying(50) NOT NULL,
    "description" "text",
    "weight_percent" integer,
    "source_id" "uuid" NOT NULL
);


ALTER TABLE "public"."course_assessments" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."course_objectives" (
    "id" "uuid" NOT NULL,
    "course_code" character varying(50) NOT NULL,
    "description" "text" NOT NULL,
    "outcome_refs" "jsonb",
    "source_id" "uuid" NOT NULL
);


ALTER TABLE "public"."course_objectives" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."course_outcomes" (
    "id" "uuid" NOT NULL,
    "course_code" character varying(50) NOT NULL,
    "description" "text" NOT NULL,
    "outcome_code" character varying(50) NOT NULL,
    "source_id" "uuid" NOT NULL
);


ALTER TABLE "public"."course_outcomes" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."course_references" (
    "id" "uuid" NOT NULL,
    "course_code" character varying(50) NOT NULL,
    "reference_text" "text" NOT NULL,
    "source_id" "uuid" NOT NULL
);


ALTER TABLE "public"."course_references" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."course_relationships" (
    "id" bigint NOT NULL,
    "course_id" bigint NOT NULL,
    "related_course_id" bigint NOT NULL,
    "relation_type" character varying(50) NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "course_relationships_check" CHECK (("course_id" <> "related_course_id"))
);


ALTER TABLE "public"."course_relationships" OWNER TO "postgres";


ALTER TABLE "public"."course_relationships" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."course_relationships_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."course_reviews" (
    "id" bigint NOT NULL,
    "comment" "text",
    "created_at" timestamp(6) without time zone NOT NULL,
    "rating" integer NOT NULL,
    "updated_at" timestamp(6) without time zone NOT NULL,
    "course_id" bigint NOT NULL,
    "student_id" bigint NOT NULL,
    CONSTRAINT "course_reviews_rating_check" CHECK ((("rating" <= 5) AND ("rating" >= 1)))
);


ALTER TABLE "public"."course_reviews" OWNER TO "postgres";


ALTER TABLE "public"."course_reviews" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."course_reviews_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."course_sessions" (
    "id" "uuid" NOT NULL,
    "activities" "text",
    "assessment_component" "text",
    "course_code" character varying(50) NOT NULL,
    "session_no" character varying(50),
    "session_type" character varying(50) NOT NULL,
    "topic" "text" NOT NULL,
    "source_id" "uuid" NOT NULL
);


ALTER TABLE "public"."course_sessions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."course_syllabus" (
    "id" "uuid" NOT NULL,
    "course_code" character varying(50) NOT NULL,
    "course_name_en" "text",
    "course_name_vi" "text",
    "created_at" timestamp(6) without time zone NOT NULL,
    "credits" integer,
    "department" "text",
    "description" "text",
    "practice_hours" integer,
    "prerequisite" "text",
    "previous_course" "text",
    "self_study_hours" integer,
    "theory_hours" integer,
    "updated_at" timestamp(6) without time zone NOT NULL,
    "source_id" "uuid" NOT NULL
);


ALTER TABLE "public"."course_syllabus" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."course_tools" (
    "id" "uuid" NOT NULL,
    "course_code" character varying(50) NOT NULL,
    "tool_name" "text" NOT NULL,
    "source_id" "uuid" NOT NULL
);


ALTER TABLE "public"."course_tools" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."course_tutorials" (
    "id" bigint NOT NULL,
    "course_id" bigint NOT NULL,
    "title" character varying(255) NOT NULL,
    "url" character varying(255) NOT NULL,
    "type" character varying(50) DEFAULT 'article'::character varying NOT NULL,
    "description" "text",
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."course_tutorials" OWNER TO "postgres";


ALTER TABLE "public"."course_tutorials" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."course_tutorials_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."course_youtube_playlists" (
    "id" bigint NOT NULL,
    "course_id" bigint NOT NULL,
    "title" character varying(255) NOT NULL,
    "url" character varying(255) NOT NULL,
    "description" "text",
    "channel_name" character varying(255),
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."course_youtube_playlists" OWNER TO "postgres";


ALTER TABLE "public"."course_youtube_playlists" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."course_youtube_playlists_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."courses" (
    "stt" bigint NOT NULL,
    "mamh" character varying(20) NOT NULL,
    "tenmh" character varying(255) NOT NULL,
    "tenmh_en" character varying(255),
    "sotc" integer DEFAULT 0 NOT NULL,
    "lt" integer DEFAULT 0 NOT NULL,
    "th" integer DEFAULT 0 NOT NULL,
    "loaimonhoc" character varying(50) NOT NULL,
    "semester" integer,
    "is_open" boolean DEFAULT true NOT NULL,
    "management_unit" character varying(100),
    "description" "text",
    "mamh_old" character varying(50),
    "equivalent_mh" character varying(255),
    "prerequisite_mh" character varying(255),
    "previous_mh" character varying(255),
    "learning_objectives" "text",
    "grading_criteria" "text",
    "topics" "jsonb" DEFAULT '[]'::"jsonb"
);


ALTER TABLE "public"."courses" OWNER TO "postgres";


ALTER TABLE "public"."courses" ALTER COLUMN "stt" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."courses_stt_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."github_repos" (
    "id" bigint NOT NULL,
    "repo_name" character varying(255) NOT NULL,
    "description" "text",
    "github_url" character varying(255) NOT NULL,
    "tech_stack" character varying(255),
    "subject_id" character varying(20),
    "display_name" character varying(255),
    "primary_language" character varying(100),
    "is_active" boolean DEFAULT true NOT NULL,
    "course_id" bigint,
    "stars" integer,
    "last_pushed_at" character varying(255),
    "readme_excerpt" "text",
    "has_readme" boolean,
    "file_tree" "text"
);


ALTER TABLE "public"."github_repos" OWNER TO "postgres";


ALTER TABLE "public"."github_repos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."github_repos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."knowledge_chunks" (
    "id" "uuid" NOT NULL,
    "source_id" "uuid" NOT NULL,
    "course_code" character varying(50),
    "chunk_index" integer NOT NULL,
    "section_title" "text",
    "chunk_text" "text" NOT NULL,
    "metadata_json" "jsonb",
    "page_from" integer,
    "page_to" integer,
    "embedding" "extensions"."vector"(4096),
    "created_at" timestamp without time zone DEFAULT "now"(),
    "chunk_kind" character varying(30) DEFAULT 'DETAIL'::character varying NOT NULL,
    "parent_chunk_id" "uuid",
    "search_text" "tsvector" GENERATED ALWAYS AS ("to_tsvector"('"simple"'::"regconfig", ((COALESCE("section_title", ''::"text") || ' '::"text") || COALESCE("chunk_text", ''::"text")))) STORED
);


ALTER TABLE "public"."knowledge_chunks" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."knowledge_sources" (
    "id" "uuid" NOT NULL,
    "source_type" character varying(100) NOT NULL,
    "title" "text",
    "file_name" "text",
    "file_path" "text",
    "url" "text",
    "content_hash" "text" NOT NULL,
    "trust_level" character varying(50) DEFAULT 'OFFICIAL'::character varying NOT NULL,
    "status" character varying(50) NOT NULL,
    "raw_text" "text",
    "error_message" "text",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."knowledge_sources" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."learning_roadmaps" (
    "id" bigint NOT NULL,
    "student_id" bigint NOT NULL,
    "title" character varying(255) NOT NULL,
    "description" "text",
    "markdown_content" "text",
    "is_public" boolean DEFAULT false NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."learning_roadmaps" OWNER TO "postgres";


ALTER TABLE "public"."learning_roadmaps" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."learning_roadmaps_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."note_code_snippets" (
    "id" bigint NOT NULL,
    "note_id" bigint NOT NULL,
    "language" character varying(50) NOT NULL,
    "code" "text" NOT NULL,
    "caption" character varying(255),
    "sort_order" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."note_code_snippets" OWNER TO "postgres";


ALTER TABLE "public"."note_code_snippets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."note_code_snippets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."notes" (
    "id" bigint NOT NULL,
    "student_id" bigint NOT NULL,
    "title" character varying(255) NOT NULL,
    "content_markdown" "text",
    "target_type" character varying(50) DEFAULT 'NONE'::"public"."note_target_type" NOT NULL,
    "target_id" bigint,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."notes" OWNER TO "postgres";


ALTER TABLE "public"."notes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."notes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."notifications" (
    "id" bigint NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "is_read" boolean NOT NULL,
    "message" character varying(255) NOT NULL,
    "target_url" character varying(255),
    "type" character varying(255) NOT NULL
);


ALTER TABLE "public"."notifications" OWNER TO "postgres";


ALTER TABLE "public"."notifications" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."notifications_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."otps" (
    "id" bigint NOT NULL,
    "email" character varying(255) NOT NULL,
    "otp_code" character varying(6) NOT NULL,
    "expires_at" timestamp without time zone NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "purpose" character varying(30) NOT NULL
);


ALTER TABLE "public"."otps" OWNER TO "postgres";


ALTER TABLE "public"."otps" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."otps_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."photobooth_frames" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "frame_id" character varying(255) NOT NULL,
    "name" character varying(255) NOT NULL,
    "display_name" character varying(255) NOT NULL,
    "photo_count" integer NOT NULL,
    "description" "text" DEFAULT ''::"text",
    "slots" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "overlay_image_url" "text",
    "filter" "text" DEFAULT 'normal'::"text",
    "background_color" "text" DEFAULT '#ffffff'::"text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "photobooth_frames_photo_count_check" CHECK (("photo_count" = ANY (ARRAY[1, 2, 3, 4, 6])))
);


ALTER TABLE "public"."photobooth_frames" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."repo_candidates" (
    "id" bigint NOT NULL,
    "course_id" bigint,
    "scan_query" character varying(255),
    "github_owner" character varying(255),
    "github_name" character varying(255),
    "github_url" character varying(255) NOT NULL,
    "description" "text",
    "primary_language" character varying(100),
    "topics" "text",
    "stars" integer,
    "forks" integer,
    "last_pushed_at" character varying(255),
    "readme_excerpt" "text",
    "has_readme" boolean,
    "file_tree" "text",
    "status" character varying(255) DEFAULT 'NEW'::character varying NOT NULL,
    "review_note" "text",
    "assigned_reviewer" character varying(50),
    "created_at" timestamp(6) without time zone NOT NULL
);


ALTER TABLE "public"."repo_candidates" OWNER TO "postgres";


ALTER TABLE "public"."repo_candidates" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."repo_candidates_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."repo_reviews" (
    "id" bigint NOT NULL,
    "comment" "text",
    "created_at" timestamp(6) without time zone NOT NULL,
    "rating" integer NOT NULL,
    "updated_at" timestamp(6) without time zone NOT NULL,
    "repo_id" bigint NOT NULL,
    "student_id" bigint NOT NULL,
    CONSTRAINT "repo_reviews_rating_check" CHECK ((("rating" <= 5) AND ("rating" >= 1)))
);


ALTER TABLE "public"."repo_reviews" OWNER TO "postgres";


ALTER TABLE "public"."repo_reviews" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."repo_reviews_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."repo_tech_stacks" (
    "repo_id" bigint NOT NULL,
    "tech_stack_id" bigint NOT NULL
);


ALTER TABLE "public"."repo_tech_stacks" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."repo_votes" (
    "id" bigint NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "vote_value" integer NOT NULL,
    "repo_id" bigint NOT NULL,
    "student_id" bigint NOT NULL
);


ALTER TABLE "public"."repo_votes" OWNER TO "postgres";


ALTER TABLE "public"."repo_votes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."repo_votes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."roadmap_items" (
    "id" bigint NOT NULL,
    "phase_id" bigint NOT NULL,
    "target_type" character varying(50) NOT NULL,
    "target_id" bigint NOT NULL,
    "title" character varying(255),
    "note" "text",
    "sort_order" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."roadmap_items" OWNER TO "postgres";


ALTER TABLE "public"."roadmap_items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."roadmap_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."roadmap_phases" (
    "id" bigint NOT NULL,
    "roadmap_id" bigint NOT NULL,
    "title" character varying(255) NOT NULL,
    "description" "text",
    "sort_order" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."roadmap_phases" OWNER TO "postgres";


ALTER TABLE "public"."roadmap_phases" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."roadmap_phases_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."student_bookmarks" (
    "id" bigint NOT NULL,
    "student_id" bigint NOT NULL,
    "target_type" character varying(255) NOT NULL,
    "target_id" bigint NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "subtitle" character varying(255),
    "title" character varying(255) NOT NULL,
    "url" character varying(255) NOT NULL
);


ALTER TABLE "public"."student_bookmarks" OWNER TO "postgres";


ALTER TABLE "public"."student_bookmarks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."student_bookmarks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."student_users" (
    "id" bigint NOT NULL,
    "student_code" character varying(255) NOT NULL,
    "full_name" character varying(255) NOT NULL,
    "email" character varying(255) NOT NULL,
    "password_hash" character varying(255) NOT NULL,
    "active" boolean DEFAULT true NOT NULL,
    "email_verified" boolean DEFAULT false NOT NULL,
    "avatar" character varying(255)
);


ALTER TABLE "public"."student_users" OWNER TO "postgres";


ALTER TABLE "public"."student_users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."student_users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tech_stacks" (
    "id" bigint NOT NULL,
    "name" character varying(120) NOT NULL,
    "repo_id" bigint
);


ALTER TABLE "public"."tech_stacks" OWNER TO "postgres";


ALTER TABLE "public"."tech_stacks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tech_stacks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tutor_registrations" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "full_name" "text" NOT NULL,
    "school" "text" NOT NULL,
    "education_level" "text" NOT NULL,
    "subject" "text" NOT NULL,
    "email" "text" NOT NULL,
    "phone" "text" NOT NULL,
    "facebook" "text",
    "zalo" "text",
    "status" "text" DEFAULT 'pending'::"text"
);


ALTER TABLE "public"."tutor_registrations" OWNER TO "postgres";


ALTER TABLE ONLY "public"."admin_users"
    ADD CONSTRAINT "admin_users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."admin_users"
    ADD CONSTRAINT "admin_users_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."chat_channels"
    ADD CONSTRAINT "chat_channels_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."chat_messages"
    ADD CONSTRAINT "chat_messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."chat_sessions"
    ADD CONSTRAINT "chat_sessions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."community_messages"
    ADD CONSTRAINT "community_messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_articles"
    ADD CONSTRAINT "course_articles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_assessments"
    ADD CONSTRAINT "course_assessments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_objectives"
    ADD CONSTRAINT "course_objectives_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_outcomes"
    ADD CONSTRAINT "course_outcomes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_references"
    ADD CONSTRAINT "course_references_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_relationships"
    ADD CONSTRAINT "course_relationships_course_id_related_course_id_key" UNIQUE ("course_id", "related_course_id");



ALTER TABLE ONLY "public"."course_relationships"
    ADD CONSTRAINT "course_relationships_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_reviews"
    ADD CONSTRAINT "course_reviews_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_sessions"
    ADD CONSTRAINT "course_sessions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_syllabus"
    ADD CONSTRAINT "course_syllabus_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_tools"
    ADD CONSTRAINT "course_tools_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_tutorials"
    ADD CONSTRAINT "course_tutorials_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_youtube_playlists"
    ADD CONSTRAINT "course_youtube_playlists_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."courses"
    ADD CONSTRAINT "courses_mamh_key" UNIQUE ("mamh");



ALTER TABLE ONLY "public"."courses"
    ADD CONSTRAINT "courses_pkey" PRIMARY KEY ("stt");



ALTER TABLE ONLY "public"."github_repos"
    ADD CONSTRAINT "github_repos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."knowledge_chunks"
    ADD CONSTRAINT "knowledge_chunks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."knowledge_sources"
    ADD CONSTRAINT "knowledge_sources_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."learning_roadmaps"
    ADD CONSTRAINT "learning_roadmaps_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."note_code_snippets"
    ADD CONSTRAINT "note_code_snippets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notes"
    ADD CONSTRAINT "notes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."otps"
    ADD CONSTRAINT "otps_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."photobooth_frames"
    ADD CONSTRAINT "photobooth_frames_frame_id_key" UNIQUE ("frame_id");



ALTER TABLE ONLY "public"."photobooth_frames"
    ADD CONSTRAINT "photobooth_frames_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."repo_candidates"
    ADD CONSTRAINT "repo_candidates_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."repo_reviews"
    ADD CONSTRAINT "repo_reviews_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."repo_tech_stacks"
    ADD CONSTRAINT "repo_tech_stacks_pkey" PRIMARY KEY ("repo_id", "tech_stack_id");



ALTER TABLE ONLY "public"."repo_votes"
    ADD CONSTRAINT "repo_votes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."roadmap_items"
    ADD CONSTRAINT "roadmap_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."roadmap_phases"
    ADD CONSTRAINT "roadmap_phases_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."student_bookmarks"
    ADD CONSTRAINT "student_bookmarks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."student_bookmarks"
    ADD CONSTRAINT "student_bookmarks_student_id_target_type_target_id_key" UNIQUE ("student_id", "target_type", "target_id");



ALTER TABLE ONLY "public"."student_users"
    ADD CONSTRAINT "student_users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."student_users"
    ADD CONSTRAINT "student_users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."student_users"
    ADD CONSTRAINT "student_users_student_code_key" UNIQUE ("student_code");



ALTER TABLE ONLY "public"."tech_stacks"
    ADD CONSTRAINT "tech_stacks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tutor_registrations"
    ADD CONSTRAINT "tutor_registrations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_reviews"
    ADD CONSTRAINT "uk_course_review_student" UNIQUE ("course_id", "student_id");



ALTER TABLE ONLY "public"."repo_reviews"
    ADD CONSTRAINT "uk_repo_review_student" UNIQUE ("repo_id", "student_id");



ALTER TABLE ONLY "public"."repo_votes"
    ADD CONSTRAINT "uk_repo_vote_student" UNIQUE ("repo_id", "student_id");



ALTER TABLE ONLY "public"."course_relationships"
    ADD CONSTRAINT "ukb26rcoxgxf69duhxiudw74oy2" UNIQUE ("course_id", "related_course_id", "relation_type");



ALTER TABLE ONLY "public"."chat_channels"
    ADD CONSTRAINT "ukgpwdv3yn6xvo9dk53cyomxdg6" UNIQUE ("channel_id");



CREATE INDEX "idx_chat_messages_session_id" ON "public"."chat_messages" USING "btree" ("session_id");



CREATE INDEX "idx_chat_sessions_student_id" ON "public"."chat_sessions" USING "btree" ("student_id");



CREATE INDEX "idx_community_messages_channel_id" ON "public"."community_messages" USING "btree" ("channel_id");



CREATE INDEX "idx_course_articles_course" ON "public"."course_articles" USING "btree" ("course_id");



CREATE INDEX "idx_course_assessments_source_id" ON "public"."course_assessments" USING "btree" ("source_id");



CREATE INDEX "idx_course_objectives_source_id" ON "public"."course_objectives" USING "btree" ("source_id");



CREATE INDEX "idx_course_outcomes_source_id" ON "public"."course_outcomes" USING "btree" ("source_id");



CREATE INDEX "idx_course_references_source_id" ON "public"."course_references" USING "btree" ("source_id");



CREATE INDEX "idx_course_relationships_related_course_id" ON "public"."course_relationships" USING "btree" ("related_course_id");



CREATE INDEX "idx_course_rels_course" ON "public"."course_relationships" USING "btree" ("course_id");



CREATE INDEX "idx_course_sessions_source_id" ON "public"."course_sessions" USING "btree" ("source_id");



CREATE INDEX "idx_course_syllabus_source_id" ON "public"."course_syllabus" USING "btree" ("source_id");



CREATE INDEX "idx_course_tools_source_id" ON "public"."course_tools" USING "btree" ("source_id");



CREATE INDEX "idx_course_tutorials_course" ON "public"."course_tutorials" USING "btree" ("course_id");



CREATE INDEX "idx_course_yt_course" ON "public"."course_youtube_playlists" USING "btree" ("course_id");



CREATE INDEX "idx_github_repos_active" ON "public"."github_repos" USING "btree" ("is_active");



CREATE INDEX "idx_github_repos_course" ON "public"."github_repos" USING "btree" ("course_id");



CREATE INDEX "idx_knowledge_chunks_code" ON "public"."knowledge_chunks" USING "btree" ("course_code");



CREATE INDEX "idx_knowledge_chunks_kind" ON "public"."knowledge_chunks" USING "btree" ("chunk_kind");



CREATE INDEX "idx_knowledge_chunks_parent" ON "public"."knowledge_chunks" USING "btree" ("parent_chunk_id");



CREATE INDEX "idx_knowledge_chunks_search_text" ON "public"."knowledge_chunks" USING "gin" ("search_text");



CREATE INDEX "idx_knowledge_chunks_source" ON "public"."knowledge_chunks" USING "btree" ("source_id");



CREATE INDEX "idx_knowledge_sources_hash" ON "public"."knowledge_sources" USING "btree" ("content_hash");



CREATE INDEX "idx_note_snippets_note" ON "public"."note_code_snippets" USING "btree" ("note_id");



CREATE INDEX "idx_notes_student" ON "public"."notes" USING "btree" ("student_id");



CREATE INDEX "idx_notes_target" ON "public"."notes" USING "btree" ("target_type", "target_id");



CREATE INDEX "idx_repo_candidates_course_id" ON "public"."repo_candidates" USING "btree" ("course_id");



CREATE INDEX "idx_repo_candidates_status" ON "public"."repo_candidates" USING "btree" ("status");



CREATE INDEX "idx_repo_tech_stacks_tech_stack_id" ON "public"."repo_tech_stacks" USING "btree" ("tech_stack_id");



CREATE INDEX "idx_repo_votes_student" ON "public"."repo_votes" USING "btree" ("student_id");



CREATE INDEX "idx_roadmap_items_phase" ON "public"."roadmap_items" USING "btree" ("phase_id");



CREATE INDEX "idx_roadmap_phases_roadmap" ON "public"."roadmap_phases" USING "btree" ("roadmap_id");



CREATE INDEX "idx_roadmaps_student" ON "public"."learning_roadmaps" USING "btree" ("student_id");



CREATE INDEX "idx_student_bookmarks_user" ON "public"."student_bookmarks" USING "btree" ("student_id");



CREATE INDEX "idx_tech_stacks_repo_id" ON "public"."tech_stacks" USING "btree" ("repo_id");



CREATE UNIQUE INDEX "uk_tech_stack_name" ON "public"."tech_stacks" USING "btree" ("name");



ALTER TABLE ONLY "public"."course_articles"
    ADD CONSTRAINT "course_articles_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "public"."courses"("stt") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."course_relationships"
    ADD CONSTRAINT "course_relationships_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "public"."courses"("stt") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."course_relationships"
    ADD CONSTRAINT "course_relationships_related_course_id_fkey" FOREIGN KEY ("related_course_id") REFERENCES "public"."courses"("stt") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."course_tutorials"
    ADD CONSTRAINT "course_tutorials_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "public"."courses"("stt") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."course_youtube_playlists"
    ADD CONSTRAINT "course_youtube_playlists_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "public"."courses"("stt") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."chat_messages"
    ADD CONSTRAINT "fk3cpkdtwdxndrjhrx3gt9q5ux9" FOREIGN KEY ("session_id") REFERENCES "public"."chat_sessions"("id");



ALTER TABLE ONLY "public"."course_assessments"
    ADD CONSTRAINT "fk5i8w1o4acctqj18j1rp1gdjvb" FOREIGN KEY ("source_id") REFERENCES "public"."knowledge_sources"("id");



ALTER TABLE ONLY "public"."course_reviews"
    ADD CONSTRAINT "fk799g8dfcye3g51ru63bfdhyb1" FOREIGN KEY ("course_id") REFERENCES "public"."courses"("stt");



ALTER TABLE ONLY "public"."chat_sessions"
    ADD CONSTRAINT "fk9d3nxk4t95oakb3x6un0m9hng" FOREIGN KEY ("student_id") REFERENCES "public"."student_users"("id");



ALTER TABLE ONLY "public"."course_objectives"
    ADD CONSTRAINT "fkbk9dli4xq9dqbvhyyk3q5pat8" FOREIGN KEY ("source_id") REFERENCES "public"."knowledge_sources"("id");



ALTER TABLE ONLY "public"."course_references"
    ADD CONSTRAINT "fkc17yha4batju4vbwymephvdta" FOREIGN KEY ("source_id") REFERENCES "public"."knowledge_sources"("id");



ALTER TABLE ONLY "public"."community_messages"
    ADD CONSTRAINT "fkcs8w16r56hc566ok2kkqcb474" FOREIGN KEY ("channel_id") REFERENCES "public"."chat_channels"("id");



ALTER TABLE ONLY "public"."course_syllabus"
    ADD CONSTRAINT "fkedir672l59ypd1c3776ti8buu" FOREIGN KEY ("source_id") REFERENCES "public"."knowledge_sources"("id");



ALTER TABLE ONLY "public"."repo_votes"
    ADD CONSTRAINT "fkhtb39ea4gfbhj4pverc5be93a" FOREIGN KEY ("repo_id") REFERENCES "public"."github_repos"("id");



ALTER TABLE ONLY "public"."course_outcomes"
    ADD CONSTRAINT "fkkdbtwgpmtkpjod5llmck74tx4" FOREIGN KEY ("source_id") REFERENCES "public"."knowledge_sources"("id");



ALTER TABLE ONLY "public"."course_tools"
    ADD CONSTRAINT "fklim5bg2t762njcl2c7qtj82la" FOREIGN KEY ("source_id") REFERENCES "public"."knowledge_sources"("id");



ALTER TABLE ONLY "public"."repo_reviews"
    ADD CONSTRAINT "fklmky0sbuwny0ir1j2g7dqh305" FOREIGN KEY ("repo_id") REFERENCES "public"."github_repos"("id");



ALTER TABLE ONLY "public"."repo_votes"
    ADD CONSTRAINT "fkm7y4nmjc6o9lsjct3d6mql8oe" FOREIGN KEY ("student_id") REFERENCES "public"."student_users"("id");



ALTER TABLE ONLY "public"."student_bookmarks"
    ADD CONSTRAINT "fkp1exvvhr7pin91wx40lb8wt88" FOREIGN KEY ("student_id") REFERENCES "public"."student_users"("id");



ALTER TABLE ONLY "public"."course_sessions"
    ADD CONSTRAINT "fkrn4gxjlpa4xka950jp7u0w4lg" FOREIGN KEY ("source_id") REFERENCES "public"."knowledge_sources"("id");



ALTER TABLE ONLY "public"."tech_stacks"
    ADD CONSTRAINT "fkwagp1wsh9266qeyqmw205i4h" FOREIGN KEY ("repo_id") REFERENCES "public"."github_repos"("id");



ALTER TABLE ONLY "public"."github_repos"
    ADD CONSTRAINT "github_repos_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "public"."courses"("stt");



ALTER TABLE ONLY "public"."knowledge_chunks"
    ADD CONSTRAINT "knowledge_chunks_source_id_fkey" FOREIGN KEY ("source_id") REFERENCES "public"."knowledge_sources"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."learning_roadmaps"
    ADD CONSTRAINT "learning_roadmaps_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "public"."student_users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."note_code_snippets"
    ADD CONSTRAINT "note_code_snippets_note_id_fkey" FOREIGN KEY ("note_id") REFERENCES "public"."notes"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."notes"
    ADD CONSTRAINT "notes_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "public"."student_users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."repo_candidates"
    ADD CONSTRAINT "repo_candidates_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "public"."courses"("stt");



ALTER TABLE ONLY "public"."repo_tech_stacks"
    ADD CONSTRAINT "repo_tech_stacks_repo_id_fkey" FOREIGN KEY ("repo_id") REFERENCES "public"."github_repos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."repo_tech_stacks"
    ADD CONSTRAINT "repo_tech_stacks_tech_stack_id_fkey" FOREIGN KEY ("tech_stack_id") REFERENCES "public"."tech_stacks"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."roadmap_items"
    ADD CONSTRAINT "roadmap_items_phase_id_fkey" FOREIGN KEY ("phase_id") REFERENCES "public"."roadmap_phases"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."roadmap_phases"
    ADD CONSTRAINT "roadmap_phases_roadmap_id_fkey" FOREIGN KEY ("roadmap_id") REFERENCES "public"."learning_roadmaps"("id") ON DELETE CASCADE;



CREATE POLICY "Deny direct API access" ON "public"."admin_users" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."chat_channels" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."chat_messages" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."chat_sessions" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."community_messages" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."course_articles" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."course_assessments" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."course_objectives" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."course_outcomes" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."course_references" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."course_relationships" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."course_reviews" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."course_sessions" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."course_syllabus" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."course_tools" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."course_tutorials" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."course_youtube_playlists" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."courses" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."github_repos" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."knowledge_chunks" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."knowledge_sources" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."learning_roadmaps" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."note_code_snippets" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."notes" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."notifications" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."otps" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."repo_candidates" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."repo_reviews" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."repo_tech_stacks" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."repo_votes" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."roadmap_items" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."roadmap_phases" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."student_bookmarks" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."student_users" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Deny direct API access" ON "public"."tech_stacks" TO "anon", "authenticated" USING (false) WITH CHECK (false);



CREATE POLICY "Public insert tutor registrations limited" ON "public"."tutor_registrations" FOR INSERT TO "anon", "authenticated" WITH CHECK (((("length"(TRIM(BOTH FROM "full_name")) >= 2) AND ("length"(TRIM(BOTH FROM "full_name")) <= 255)) AND (("length"(TRIM(BOTH FROM "school")) >= 2) AND ("length"(TRIM(BOTH FROM "school")) <= 255)) AND (("length"(TRIM(BOTH FROM "education_level")) >= 2) AND ("length"(TRIM(BOTH FROM "education_level")) <= 255)) AND (("length"(TRIM(BOTH FROM "subject")) >= 2) AND ("length"(TRIM(BOTH FROM "subject")) <= 255)) AND (("length"(TRIM(BOTH FROM "email")) >= 5) AND ("length"(TRIM(BOTH FROM "email")) <= 320)) AND ("email" ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'::"text") AND (("length"(TRIM(BOTH FROM "phone")) >= 7) AND ("length"(TRIM(BOTH FROM "phone")) <= 32)) AND (COALESCE("status", 'pending'::"text") = 'pending'::"text")));



CREATE POLICY "Public read photobooth_frames" ON "public"."photobooth_frames" FOR SELECT USING (true);



ALTER TABLE "public"."admin_users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."chat_channels" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."chat_messages" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."chat_sessions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."community_messages" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."course_articles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."course_assessments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."course_objectives" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."course_outcomes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."course_references" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."course_relationships" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."course_reviews" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."course_sessions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."course_syllabus" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."course_tools" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."course_tutorials" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."course_youtube_playlists" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."courses" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."github_repos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."knowledge_chunks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."knowledge_sources" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."learning_roadmaps" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."note_code_snippets" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."notes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."notifications" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."otps" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."photobooth_frames" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."repo_candidates" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."repo_reviews" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."repo_tech_stacks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."repo_votes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."roadmap_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."roadmap_phases" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."student_bookmarks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."student_users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tech_stacks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tutor_registrations" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



REVOKE ALL ON FUNCTION "public"."rls_auto_enable"() FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."rls_auto_enable"() TO "service_role";



GRANT ALL ON TABLE "public"."admin_users" TO "anon";
GRANT ALL ON TABLE "public"."admin_users" TO "authenticated";
GRANT ALL ON TABLE "public"."admin_users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."admin_users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."admin_users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."admin_users_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."chat_channels" TO "anon";
GRANT ALL ON TABLE "public"."chat_channels" TO "authenticated";
GRANT ALL ON TABLE "public"."chat_channels" TO "service_role";



GRANT ALL ON SEQUENCE "public"."chat_channels_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."chat_channels_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."chat_channels_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."chat_messages" TO "anon";
GRANT ALL ON TABLE "public"."chat_messages" TO "authenticated";
GRANT ALL ON TABLE "public"."chat_messages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."chat_messages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."chat_messages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."chat_messages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."chat_sessions" TO "anon";
GRANT ALL ON TABLE "public"."chat_sessions" TO "authenticated";
GRANT ALL ON TABLE "public"."chat_sessions" TO "service_role";



GRANT ALL ON TABLE "public"."community_messages" TO "anon";
GRANT ALL ON TABLE "public"."community_messages" TO "authenticated";
GRANT ALL ON TABLE "public"."community_messages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."community_messages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."community_messages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."community_messages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."course_articles" TO "anon";
GRANT ALL ON TABLE "public"."course_articles" TO "authenticated";
GRANT ALL ON TABLE "public"."course_articles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."course_articles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."course_articles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."course_articles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."course_assessments" TO "anon";
GRANT ALL ON TABLE "public"."course_assessments" TO "authenticated";
GRANT ALL ON TABLE "public"."course_assessments" TO "service_role";



GRANT ALL ON TABLE "public"."course_objectives" TO "anon";
GRANT ALL ON TABLE "public"."course_objectives" TO "authenticated";
GRANT ALL ON TABLE "public"."course_objectives" TO "service_role";



GRANT ALL ON TABLE "public"."course_outcomes" TO "anon";
GRANT ALL ON TABLE "public"."course_outcomes" TO "authenticated";
GRANT ALL ON TABLE "public"."course_outcomes" TO "service_role";



GRANT ALL ON TABLE "public"."course_references" TO "anon";
GRANT ALL ON TABLE "public"."course_references" TO "authenticated";
GRANT ALL ON TABLE "public"."course_references" TO "service_role";



GRANT ALL ON TABLE "public"."course_relationships" TO "anon";
GRANT ALL ON TABLE "public"."course_relationships" TO "authenticated";
GRANT ALL ON TABLE "public"."course_relationships" TO "service_role";



GRANT ALL ON SEQUENCE "public"."course_relationships_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."course_relationships_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."course_relationships_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."course_reviews" TO "anon";
GRANT ALL ON TABLE "public"."course_reviews" TO "authenticated";
GRANT ALL ON TABLE "public"."course_reviews" TO "service_role";



GRANT ALL ON SEQUENCE "public"."course_reviews_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."course_reviews_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."course_reviews_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."course_sessions" TO "anon";
GRANT ALL ON TABLE "public"."course_sessions" TO "authenticated";
GRANT ALL ON TABLE "public"."course_sessions" TO "service_role";



GRANT ALL ON TABLE "public"."course_syllabus" TO "anon";
GRANT ALL ON TABLE "public"."course_syllabus" TO "authenticated";
GRANT ALL ON TABLE "public"."course_syllabus" TO "service_role";



GRANT ALL ON TABLE "public"."course_tools" TO "anon";
GRANT ALL ON TABLE "public"."course_tools" TO "authenticated";
GRANT ALL ON TABLE "public"."course_tools" TO "service_role";



GRANT ALL ON TABLE "public"."course_tutorials" TO "anon";
GRANT ALL ON TABLE "public"."course_tutorials" TO "authenticated";
GRANT ALL ON TABLE "public"."course_tutorials" TO "service_role";



GRANT ALL ON SEQUENCE "public"."course_tutorials_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."course_tutorials_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."course_tutorials_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."course_youtube_playlists" TO "anon";
GRANT ALL ON TABLE "public"."course_youtube_playlists" TO "authenticated";
GRANT ALL ON TABLE "public"."course_youtube_playlists" TO "service_role";



GRANT ALL ON SEQUENCE "public"."course_youtube_playlists_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."course_youtube_playlists_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."course_youtube_playlists_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."courses" TO "anon";
GRANT ALL ON TABLE "public"."courses" TO "authenticated";
GRANT ALL ON TABLE "public"."courses" TO "service_role";



GRANT ALL ON SEQUENCE "public"."courses_stt_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."courses_stt_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."courses_stt_seq" TO "service_role";



GRANT ALL ON TABLE "public"."github_repos" TO "anon";
GRANT ALL ON TABLE "public"."github_repos" TO "authenticated";
GRANT ALL ON TABLE "public"."github_repos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."github_repos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."github_repos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."github_repos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."knowledge_chunks" TO "anon";
GRANT ALL ON TABLE "public"."knowledge_chunks" TO "authenticated";
GRANT ALL ON TABLE "public"."knowledge_chunks" TO "service_role";



GRANT ALL ON TABLE "public"."knowledge_sources" TO "anon";
GRANT ALL ON TABLE "public"."knowledge_sources" TO "authenticated";
GRANT ALL ON TABLE "public"."knowledge_sources" TO "service_role";



GRANT ALL ON TABLE "public"."learning_roadmaps" TO "anon";
GRANT ALL ON TABLE "public"."learning_roadmaps" TO "authenticated";
GRANT ALL ON TABLE "public"."learning_roadmaps" TO "service_role";



GRANT ALL ON SEQUENCE "public"."learning_roadmaps_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."learning_roadmaps_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."learning_roadmaps_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."note_code_snippets" TO "anon";
GRANT ALL ON TABLE "public"."note_code_snippets" TO "authenticated";
GRANT ALL ON TABLE "public"."note_code_snippets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."note_code_snippets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."note_code_snippets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."note_code_snippets_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."notes" TO "anon";
GRANT ALL ON TABLE "public"."notes" TO "authenticated";
GRANT ALL ON TABLE "public"."notes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."notes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."notes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."notes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."notifications" TO "anon";
GRANT ALL ON TABLE "public"."notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."notifications" TO "service_role";



GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."otps" TO "anon";
GRANT ALL ON TABLE "public"."otps" TO "authenticated";
GRANT ALL ON TABLE "public"."otps" TO "service_role";



GRANT ALL ON SEQUENCE "public"."otps_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."otps_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."otps_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."photobooth_frames" TO "anon";
GRANT ALL ON TABLE "public"."photobooth_frames" TO "authenticated";
GRANT ALL ON TABLE "public"."photobooth_frames" TO "service_role";



GRANT ALL ON TABLE "public"."repo_candidates" TO "anon";
GRANT ALL ON TABLE "public"."repo_candidates" TO "authenticated";
GRANT ALL ON TABLE "public"."repo_candidates" TO "service_role";



GRANT ALL ON SEQUENCE "public"."repo_candidates_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."repo_candidates_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."repo_candidates_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."repo_reviews" TO "anon";
GRANT ALL ON TABLE "public"."repo_reviews" TO "authenticated";
GRANT ALL ON TABLE "public"."repo_reviews" TO "service_role";



GRANT ALL ON SEQUENCE "public"."repo_reviews_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."repo_reviews_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."repo_reviews_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."repo_tech_stacks" TO "anon";
GRANT ALL ON TABLE "public"."repo_tech_stacks" TO "authenticated";
GRANT ALL ON TABLE "public"."repo_tech_stacks" TO "service_role";



GRANT ALL ON TABLE "public"."repo_votes" TO "anon";
GRANT ALL ON TABLE "public"."repo_votes" TO "authenticated";
GRANT ALL ON TABLE "public"."repo_votes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."repo_votes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."repo_votes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."repo_votes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."roadmap_items" TO "anon";
GRANT ALL ON TABLE "public"."roadmap_items" TO "authenticated";
GRANT ALL ON TABLE "public"."roadmap_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."roadmap_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."roadmap_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."roadmap_items_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."roadmap_phases" TO "anon";
GRANT ALL ON TABLE "public"."roadmap_phases" TO "authenticated";
GRANT ALL ON TABLE "public"."roadmap_phases" TO "service_role";



GRANT ALL ON SEQUENCE "public"."roadmap_phases_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."roadmap_phases_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."roadmap_phases_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."student_bookmarks" TO "anon";
GRANT ALL ON TABLE "public"."student_bookmarks" TO "authenticated";
GRANT ALL ON TABLE "public"."student_bookmarks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."student_bookmarks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."student_bookmarks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."student_bookmarks_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."student_users" TO "anon";
GRANT ALL ON TABLE "public"."student_users" TO "authenticated";
GRANT ALL ON TABLE "public"."student_users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."student_users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."student_users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."student_users_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tech_stacks" TO "anon";
GRANT ALL ON TABLE "public"."tech_stacks" TO "authenticated";
GRANT ALL ON TABLE "public"."tech_stacks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tech_stacks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tech_stacks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tech_stacks_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tutor_registrations" TO "anon";
GRANT ALL ON TABLE "public"."tutor_registrations" TO "authenticated";
GRANT ALL ON TABLE "public"."tutor_registrations" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";



ALTER TABLE "public"."chat_channels"
    ADD CONSTRAINT "chat_channels_type_check"
    CHECK (((type)::text = ANY ((ARRAY['GENERAL'::character varying, 'COURSE'::character varying, 'TECH_STACK'::character varying])::text[])))
    NOT VALID;

ALTER TABLE "public"."chat_channels"
    VALIDATE CONSTRAINT "chat_channels_type_check";

ALTER TABLE "public"."otps"
    ADD CONSTRAINT "otps_purpose_check"
    CHECK (((purpose)::text = ANY ((ARRAY['EMAIL_VERIFICATION'::character varying, 'PASSWORD_RESET'::character varying])::text[])))
    NOT VALID;

ALTER TABLE "public"."otps"
    VALIDATE CONSTRAINT "otps_purpose_check";



-- Reconstructed from remote supabase_migrations.schema_migrations for local history sync.
CREATE TABLE IF NOT EXISTS public.tutor_registrations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT now(),
    full_name TEXT NOT NULL,
    school TEXT NOT NULL,
    education_level TEXT NOT NULL, -- THPT or Äáº¡i há»c
    subject TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    facebook TEXT,
    zalo TEXT,
    status TEXT DEFAULT 'pending'
);

-- Enable RLS
ALTER TABLE public.tutor_registrations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Insert Access" ON public.tutor_registrations FOR INSERT WITH CHECK (true);
CREATE POLICY "Admin All Access" ON public.tutor_registrations FOR ALL USING (auth.role() = 'authenticated');




-- Reconstructed from remote supabase_migrations.schema_migrations for local history sync.
ALTER TABLE public.courses
ADD COLUMN IF NOT EXISTS tenmh_en character varying(255),
ADD COLUMN IF NOT EXISTS is_open boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS management_unit character varying(100),
ADD COLUMN IF NOT EXISTS mamh_old character varying(50),
ADD COLUMN IF NOT EXISTS equivalent_mh text,
ADD COLUMN IF NOT EXISTS prerequisite_mh text,
ADD COLUMN IF NOT EXISTS previous_mh text;



-- Reconstructed from remote supabase_migrations.schema_migrations for local history sync.
-- Add indexes for foreign keys reported by Supabase performance advisors.
CREATE INDEX IF NOT EXISTS idx_community_messages_channel_id
    ON public.community_messages(channel_id);

CREATE INDEX IF NOT EXISTS idx_course_assessments_source_id
    ON public.course_assessments(source_id);

CREATE INDEX IF NOT EXISTS idx_course_objectives_source_id
    ON public.course_objectives(source_id);

CREATE INDEX IF NOT EXISTS idx_course_outcomes_source_id
    ON public.course_outcomes(source_id);

CREATE INDEX IF NOT EXISTS idx_course_references_source_id
    ON public.course_references(source_id);

CREATE INDEX IF NOT EXISTS idx_course_relationships_related_course_id
    ON public.course_relationships(related_course_id);

CREATE INDEX IF NOT EXISTS idx_course_sessions_source_id
    ON public.course_sessions(source_id);

CREATE INDEX IF NOT EXISTS idx_course_syllabus_source_id
    ON public.course_syllabus(source_id);

CREATE INDEX IF NOT EXISTS idx_course_tools_source_id
    ON public.course_tools(source_id);

CREATE INDEX IF NOT EXISTS idx_repo_candidates_course_id
    ON public.repo_candidates(course_id);

CREATE INDEX IF NOT EXISTS idx_repo_tech_stacks_tech_stack_id
    ON public.repo_tech_stacks(tech_stack_id);

CREATE INDEX IF NOT EXISTS idx_tech_stacks_repo_id
    ON public.tech_stacks(repo_id);

-- Photobooth frame writes must go through the authenticated Spring admin API.
-- Public direct DB access only needs read permission for published frames.
DROP POLICY IF EXISTS "Public insert photobooth_frames" ON public.photobooth_frames;
DROP POLICY IF EXISTS "Public update photobooth_frames" ON public.photobooth_frames;
DROP POLICY IF EXISTS "Public delete photobooth_frames" ON public.photobooth_frames;

-- The helper function is SECURITY DEFINER; it should not be executable by
-- anonymous or authenticated API roles.
REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM anon;
REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM authenticated;




-- Reconstructed from remote supabase_migrations.schema_migrations for local history sync.
-- Remove duplicate bookmark uniqueness created by mixed Hibernate/manual DDL.
-- The named application constraint remains in place.
ALTER TABLE public.student_bookmarks
    DROP CONSTRAINT IF EXISTS uk9pk7ct27f5eseu5adcp0322wv;

-- Public buckets can serve public object URLs without a broad storage.objects
-- SELECT policy that also permits listing every object in the bucket.
DROP POLICY IF EXISTS "Public read access" ON storage.objects;

-- This table is not used by the Spring backend. If kept for public Data API
-- intake, allow only minimally valid pending submissions and avoid broad ALL
-- access via auth.role().
DROP POLICY IF EXISTS "Admin All Access" ON public.tutor_registrations;
DROP POLICY IF EXISTS "Public Insert Access" ON public.tutor_registrations;
DROP POLICY IF EXISTS "Public insert tutor registrations limited" ON public.tutor_registrations;

CREATE POLICY "Public insert tutor registrations limited"
ON public.tutor_registrations
FOR INSERT
TO anon, authenticated
WITH CHECK (
    length(trim(full_name)) BETWEEN 2 AND 255
    AND length(trim(school)) BETWEEN 2 AND 255
    AND length(trim(education_level)) BETWEEN 2 AND 255
    AND length(trim(subject)) BETWEEN 2 AND 255
    AND length(trim(email)) BETWEEN 5 AND 320
    AND email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
    AND length(trim(phone)) BETWEEN 7 AND 32
    AND coalesce(status, 'pending') = 'pending'
);



-- Reconstructed from remote supabase_migrations.schema_migrations for local history sync.
-- Most DevOrbit tables are owned by the Spring Boot API, not Supabase Auth.
-- Make the direct Data API posture explicit: anon/authenticated cannot access
-- these tables directly. The backend JDBC connection is unaffected.
DO $$
DECLARE
    table_name text;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'admin_users',
        'chat_channels',
        'chat_messages',
        'chat_sessions',
        'community_messages',
        'course_articles',
        'course_assessments',
        'course_objectives',
        'course_outcomes',
        'course_references',
        'course_relationships',
        'course_reviews',
        'course_sessions',
        'course_syllabus',
        'course_tools',
        'course_tutorials',
        'course_youtube_playlists',
        'courses',
        'github_repos',
        'knowledge_chunks',
        'knowledge_sources',
        'learning_roadmaps',
        'note_code_snippets',
        'notes',
        'otps',
        'repo_candidates',
        'repo_reviews',
        'repo_tech_stacks',
        'repo_votes',
        'roadmap_items',
        'roadmap_phases',
        'student_bookmarks',
        'student_users',
        'tech_stacks'
    ]
    LOOP
        IF NOT EXISTS (
            SELECT 1
            FROM pg_policies
            WHERE schemaname = 'public'
              AND tablename = table_name
              AND policyname = 'Deny direct API access'
        ) THEN
            EXECUTE format(
                'CREATE POLICY "Deny direct API access" ON public.%I FOR ALL TO anon, authenticated USING (false) WITH CHECK (false)',
                table_name
            );
        END IF;
    END LOOP;
END $$;




-- Reconstructed from remote supabase_migrations.schema_migrations for local history sync.
-- Supabase recommends keeping extensions outside the exposed public schema.
-- The backend uses schema-qualified extensions.vector after this migration.
CREATE SCHEMA IF NOT EXISTS extensions;
ALTER EXTENSION vector SET SCHEMA extensions;




-- Synchronize live Supabase posture with backend-owned database rules.
-- Rollback:
--   DROP POLICY IF EXISTS "Deny direct API access" ON public.notifications;
--   DROP INDEX IF EXISTS public.idx_repo_votes_student;
--   CREATE INDEX IF NOT EXISTS idx_photobooth_frames_frame_id ON public.photobooth_frames(frame_id);
--   DROP POLICY IF EXISTS "Public read photobooth storage buckets" ON storage.objects;
--   CREATE POLICY "Allow public read ify4b9_0" ON storage.objects FOR SELECT TO public USING (true);
--   CREATE POLICY "Allow public upload ify4b9_0" ON storage.objects FOR INSERT TO public WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_repo_votes_student
    ON public.repo_votes(student_id);

DROP INDEX IF EXISTS public.idx_photobooth_frames_frame_id;

DO $$
BEGIN
    IF to_regclass('public.notifications') IS NOT NULL
       AND NOT EXISTS (
           SELECT 1
           FROM pg_policies
           WHERE schemaname = 'public'
             AND tablename = 'notifications'
             AND policyname = 'Deny direct API access'
       ) THEN
        CREATE POLICY "Deny direct API access"
        ON public.notifications
        FOR ALL
        TO anon, authenticated
        USING (false)
        WITH CHECK (false);
    END IF;
END $$;

DO $$
BEGIN
    IF to_regclass('storage.objects') IS NOT NULL THEN
        DROP POLICY IF EXISTS "Public read access" ON storage.objects;
        DROP POLICY IF EXISTS "Allow public upload ify4b9_0" ON storage.objects;
        DROP POLICY IF EXISTS "Allow public read ify4b9_0" ON storage.objects;
        DROP POLICY IF EXISTS "Public read photobooth storage buckets" ON storage.objects;

        CREATE POLICY "Public read photobooth storage buckets"
        ON storage.objects
        FOR SELECT
        TO public
        USING (bucket_id IN ('devorbit', 'frame-overlays'));
    END IF;
END $$;



-- Normalize CHECK constraint definitions so Supabase shadow diffs reconstruct
-- the same public schema. This does not change allowed values.
-- Rollback: re-run the same statements; the logical constraints are unchanged.

ALTER TABLE public.chat_channels
    DROP CONSTRAINT IF EXISTS chat_channels_type_check;

ALTER TABLE public.chat_channels
    ADD CONSTRAINT chat_channels_type_check
    CHECK (((type)::text = ANY ((ARRAY['GENERAL'::character varying, 'COURSE'::character varying, 'TECH_STACK'::character varying])::text[])))
    NOT VALID;

ALTER TABLE public.chat_channels
    VALIDATE CONSTRAINT chat_channels_type_check;

ALTER TABLE public.otps
    DROP CONSTRAINT IF EXISTS otps_purpose_check;

ALTER TABLE public.otps
    ADD CONSTRAINT otps_purpose_check
    CHECK (((purpose)::text = ANY ((ARRAY['EMAIL_VERIFICATION'::character varying, 'PASSWORD_RESET'::character varying])::text[])))
    NOT VALID;

ALTER TABLE public.otps
    VALIDATE CONSTRAINT otps_purpose_check;



-- Add deleted column to community_messages table and create index
ALTER TABLE community_messages
    ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX idx_community_messages_deleted ON community_messages(deleted);



-- Migration: Deactivate courses that are no longer open based on the course catalog markdown.
-- Set all courses to is_open = false
UPDATE public.courses SET is_open = false;

-- Set active courses to is_open = true based on the parsed list of active course codes
UPDATE public.courses SET is_open = true WHERE mamh IN (
    'ACCT3603', 'ACCT5123', 'ADENG1', 'ADENG2', 'ADENG3', 'ADENG4', 'AI001', 'AI002',
    'AI301', 'AI302', 'AI503', 'AI504', 'AI505', 'BCH058', 'BOQC1', 'BUS1125',
    'CE005', 'CE006', 'CE103', 'CE105', 'CE118', 'CE119', 'CE121', 'CE122',
    'CE124', 'CE125', 'CE126', 'CE201', 'CE206', 'CE207', 'CE208', 'CE212',
    'CE213', 'CE222', 'CE224', 'CE226', 'CE232', 'CE233', 'CE3031', 'CE304',
    'CE313', 'CE315', 'CE317', 'CE318', 'CE320', 'CE323', 'CE331', 'CE332',
    'CE333', 'CE334', 'CE335', 'CE336', 'CE337', 'CE338', 'CE339', 'CE340',
    'CE341', 'CE342', 'CE343', 'CE344', 'CE345', 'CE346', 'CE347', 'PE231',
    'CE348', 'CE349', 'CE350', 'CE351', 'CE352', 'CE353', 'CE405', 'CE406',
    'CE407', 'CE408', 'CE409', 'CE410', 'CE411', 'CE412', 'CE413', 'CE421',
    'CE432', 'CE433', 'CE434', 'CE435', 'CE436', 'CE437', 'CE438', 'CE439',
    'CE440', 'CE441', 'CE442', 'CE501', 'CE502', 'CE505', 'CE506', 'CE507',
    'CE508', 'CE510', 'CE511', 'CE512', 'CNBU009', 'CNBU101', 'CNBU102', 'CNBU103',
    'CNBU104', 'CNBU105', 'CNBU106', 'CNBU107', 'CNBU108', 'CNBU201', 'CNBU202', 'CNBU203',
    'CNBU204', 'CNBU205', 'CS005', 'CS105', 'CS106', 'CS110', 'CS111', 'CS1113',
    'CS112', 'CS113', 'CS114', 'CS115', 'CS116', 'CS117', 'CS211', 'CS2133',
    'CS2134', 'CS214', 'CS217', 'CS221', 'CS222', 'CS226', 'CS229', 'CS231',
    'CS232', 'CS2433', 'CS302', 'CS311', 'CS312', 'CS313', 'CS314', 'CS315',
    'CS316', 'CS317', 'CS321', 'CS323', 'CS324', 'CS325', 'CS326', 'CS331',
    'CS332', 'CS333', 'CS335', 'CS336', 'CS3363', 'CS337', 'CS3373', 'CS338',
    'CS339', 'CS3423', 'CS3443', 'CS3613', 'CS3653', 'CS405', 'CS406', 'CS409',
    'CS410', 'CS412', 'CS414', 'CS4143', 'CS4153', 'CS419', 'CS420', 'CS4243',
    'CS4273', 'CS4283', 'CS431', 'CS4323', 'CS4343', 'CS4793', 'CS5000', 'CS5030',
    'CS5031', 'CS505', 'CS511', 'CS519', 'CS521', 'CS522', 'CS523', 'CS524',
    'CS525', 'CS526', 'CS527', 'CS528', 'CS529', 'CS530', 'CS532', 'CS534',
    'CS535', 'CS5423', 'CS5433', 'CS551', 'CS553', 'CS554', 'CSBU002', 'CSBU005',
    'CSBU016', 'CSBU101', 'CSBU102', 'CSBU103', 'CSBU104', 'CSBU105', 'CSBU106', 'CSBU107',
    'CSBU108', 'CSBU109', 'CSBU110', 'CSBU111', 'CSBU112', 'CSBU201', 'CSBU202', 'CSBU203',
    'CSBU204', 'CSBU205', 'CU001', 'DAI015', 'DS005', 'DS101', 'DS102', 'DS103',
    'DS104', 'DS106', 'DS107', 'DS108', 'DS111', 'DS200', 'DS201', 'DS202',
    'DS203', 'DS204', 'DS207', 'DS300', 'DS301', 'DS302', 'DS303', 'DS304',
    'DS305', 'DS306', 'DS307', 'DS308', 'DS309', 'DS310', 'DS311', 'DS312',
    'DS313', 'DS314', 'DS315', 'DS316', 'DS317', 'DS318', 'DS319', 'DS320',
    'DS321', 'DS322', 'DS323', 'DS324', 'DS325', 'DS326', 'DS327', 'DS400',
    'DS501', 'DS502', 'DS505', 'DTH039', 'EC001', 'EC002', 'EC003', 'EC005',
    'EC101', 'EC201', 'EC204', 'EC208', 'EC213', 'EC214', 'EC222', 'EC229',
    'EC232', 'EC304', 'EC311', 'EC312', 'EC331', 'EC332', 'EC333', 'EC334',
    'EC335', 'EC336', 'EC337', 'EC338', 'EC401', 'EC402', 'EC403', 'EC404',
    'EC405', 'EN001.CO', 'EN001.GE', 'EN002.CO', 'EN002.GE', 'ENG01', 'ENG02',
    'ENG03', 'ENG04', 'ENG05', 'ENG06', 'ENG07', 'ENGA1', 'ENGA2', 'ENGL1113',
    'ENGL1213', 'GDH075', 'IE005', 'IE101', 'IE102', 'IE103', 'IE104', 'IE105',
    'IE106', 'IE108', 'IE201', 'IE203', 'IE204', 'IE205', 'IE206', 'IE207',
    'IE212', 'IE213', 'IE216', 'IE218', 'IE221', 'IE223', 'IE225', 'IE226',
    'IE227', 'IE228', 'IE229', 'IE230', 'IE231', 'IE232', 'IE233', 'IE301',
    'IE302', 'IE303', 'IE304', 'IE305', 'IE307', 'IE309', 'IE310', 'IE313',
    'IE400', 'IE401', 'IE402', 'IE403', 'IE405', 'IE406', 'IE501', 'IE502',
    'IE505', 'IEM4733', 'IEM5723', 'INI01', 'INT001', 'INT002', 'INT003',
    'INT004', 'INT005', 'INT006', 'IS005', 'IS105', 'IS201', 'IS207', 'IS208',
    'IS210', 'IS211', 'IS212', 'IS215', 'IS216', 'IS217', 'IS220', 'IS232',
    'IS251', 'IS252', 'IS254', 'IS311', 'IS332', 'IS334', 'IS335', 'IS336',
    'IS339', 'IS340', 'IS341', 'IS342', 'IS344', 'IS345', 'IS346', 'IS347',
    'IS348', 'IS349', 'IS351', 'IS352', 'IS353', 'IS354', 'IS355', 'IS356',
    'IS357', 'IS358', 'IS360', 'IS361', 'IS362', 'IS363', 'IS364', 'IS401',
    'IS402', 'IS403', 'IS405', 'IS406', 'IS407', 'IS502', 'IS503', 'IS505',
    'IS6301', 'IT001', 'IT002', 'IT003', 'IT004', 'IT005', 'IT006', 'IT007',
    'IT008', 'IT010', 'IT011', 'IT012', 'IT013', 'ITNT005', 'JAN01', 'JAN02',
    'JAN03', 'JAN04', 'JAN05', 'JAN06', 'JAN07', 'JAN08', 'JANHU', 'MA003',
    'MA004', 'MA005', 'MA006', 'MATH2144', 'MATH2153', 'MATH2154', 'MATH3013',
    'ME001', 'MKTG4223', 'MKTG5883', 'MM001', 'MM002', 'MM003', 'MM004',
    'MM005', 'MM006', 'MM007', 'MM008', 'MM101', 'MM102', 'MM103', 'MM104',
    'MM105', 'MM106', 'MM107', 'MM108', 'MM109', 'MM110', 'MM201', 'MM202',
    'MM203', 'MM204', 'MM205', 'MM206', 'MM207', 'MM208', 'MM209', 'MM210',
    'MM211', 'MM212', 'MM213', 'MM214', 'MM215', 'MM216', 'MM217', 'MM218',
    'MM219', 'MM220', 'MM221', 'MM222', 'MM223', 'MM224', 'MM301', 'MM302',
    'MM304', 'MM504', 'MM505', 'MM506', 'MSIS207', 'MSIS2433', 'MSIS3033',
    'MSIS3233', 'MSIS3242', 'MSIS3243', 'MSIS3303', 'MSIS4013', 'MSIS402',
    'MSIS405', 'MSIS406', 'MSIS4133', 'MSIS4243', 'MSIS4263', 'MSIS4443',
    'MSIS4523', 'MSIS5723', 'NHJP1', 'NHJP2', 'NNH050', 'NT005', 'NT015',
    'NT101', 'NT103', 'NT104', 'NT105', 'NT106', 'NT109', 'NT113', 'NT114',
    'NT117', 'NT118', 'NT121', 'NT131', 'NT132', 'NT133', 'NT137', 'NT140',
    'NT201', 'NT204', 'NT205', 'NT207', 'NT208', 'NT209', 'NT210', 'NT211',
    'NT212', 'NT213', 'NT215', 'NT216', 'NT219', 'NT230', 'NT303', 'NT310',
    'NT311', 'NT312', 'NT330', 'NT331', 'NT332', 'NT333', 'NT334', 'NT402',
    'NT405', 'NT504', 'NT505', 'NT506', 'NT508', 'NT521', 'NT522', 'NT523',
    'NT524', 'NT531', 'NT532', 'NT533', 'NT534', 'NT535', 'NT536', 'NT537',
    'NT538', 'NT539', 'NT540', 'NT541', 'NT542', 'NT543', 'NT544', 'NT545',
    'NT546', 'NT547', 'NT548', 'NT549', 'PE231', 'PE232', 'PH001', 'PH002',
    'PHYS1114', 'PHYS1214', 'PHYS1215', 'QTE111', 'SC203', 'SE005', 'SE100',
    'SE101', 'SE102', 'SE104', 'SE106', 'SE109', 'SE111', 'SE112', 'SE113',
    'SE114', 'SE115', 'SE116', 'SE117', 'SE121', 'SE122', 'SE214', 'SE215',
    'SE220', 'SE221', 'SE301', 'SE310', 'SE313', 'SE314', 'SE315', 'SE316',
    'SE317', 'SE320', 'SE325', 'SE327', 'SE328', 'SE329', 'SE330', 'SE331',
    'SE332', 'SE334', 'SE343', 'SE344', 'SE346', 'SE347', 'SE348', 'SE350',
    'SE351', 'SE352', 'SE354', 'SE355', 'SE356', 'SE357', 'SE358', 'SE359',
    'SE360', 'SE361', 'SE362', 'SE363', 'SE364', 'SE365', 'SE400', 'SE401',
    'SE403', 'SE404', 'SE405', 'SE406', 'SE407', 'SE408', 'SE409', 'SE417',
    'SE501', 'SE502', 'SE503', 'SE505', 'SE506', 'SE507', 'SPCH2713', 'SPCH3723',
    'SS003', 'SS004', 'SS006', 'SS007', 'SS008', 'SS009', 'SS010', 'STAT3013',
    'STAT4033', 'THU086', 'THU107', 'TLH025', 'TOEIC 450', 'TOEIC450'
);




--
-- Name: community_presences; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS "public"."community_presences" (
    "id" bigint NOT NULL,
    "session_id" character varying(255) NOT NULL,
    "subscription_id" character varying(255) NOT NULL,
    "channel_id" bigint NOT NULL,
    "student_code" character varying(255) NOT NULL,
    "created_at" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE "public"."community_presences" OWNER TO "postgres";

ALTER TABLE "public"."community_presences" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."community_presences_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."community_presences"
    ADD CONSTRAINT "community_presences_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."community_presences"
    ADD CONSTRAINT "fk_community_presences_channel" FOREIGN KEY ("channel_id") REFERENCES "public"."chat_channels"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."community_presences"
    ADD CONSTRAINT "fk_community_presences_student" FOREIGN KEY ("student_code") REFERENCES "public"."student_users"("student_code") ON DELETE CASCADE;

CREATE POLICY "Deny direct API access" ON "public"."community_presences" TO "anon", "authenticated" USING (false) WITH CHECK (false);

ALTER TABLE "public"."community_presences" ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE "public"."community_presences" TO "anon";
GRANT ALL ON TABLE "public"."community_presences" TO "authenticated";
GRANT ALL ON TABLE "public"."community_presences" TO "postgres";
GRANT ALL ON TABLE "public"."community_presences" TO "service_role";

-- ============================================================
-- 2026-06-23: group plan tables for collaborative task management
-- ============================================================

CREATE TABLE IF NOT EXISTS public.group_plans (
    id BIGSERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    creator_student_code TEXT NOT NULL,
    deadline DATE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.group_plan_members (
    id BIGSERIAL PRIMARY KEY,
    group_plan_id BIGINT NOT NULL REFERENCES public.group_plans(id) ON DELETE CASCADE,
    student_code TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    invited_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    responded_at TIMESTAMP WITH TIME ZONE,
    UNIQUE(group_plan_id, student_code)
);

CREATE TABLE IF NOT EXISTS public.group_tasks (
    id BIGSERIAL PRIMARY KEY,
    group_plan_id BIGINT NOT NULL REFERENCES public.group_plans(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    assigned_to TEXT,
    deadline DATE,
    completed BOOLEAN NOT NULL DEFAULT false,
    created_by TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    delete_requested BOOLEAN NOT NULL DEFAULT false,
    delete_requested_by TEXT,
    updated_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE public.student_notifications
    ADD COLUMN IF NOT EXISTS group_plan_id BIGINT
    REFERENCES public.group_plans(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_group_plan_members_student_code
    ON public.group_plan_members(student_code);

CREATE INDEX IF NOT EXISTS idx_group_plan_members_plan_id
    ON public.group_plan_members(group_plan_id);

CREATE INDEX IF NOT EXISTS idx_group_tasks_plan_id
    ON public.group_tasks(group_plan_id);

CREATE INDEX IF NOT EXISTS idx_group_tasks_assigned_to
    ON public.group_tasks(assigned_to);

ALTER TABLE public.group_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_plan_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Deny direct API access" ON public.group_plans FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);
CREATE POLICY "Deny direct API access" ON public.group_plan_members FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);
CREATE POLICY "Deny direct API access" ON public.group_tasks FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);

GRANT ALL ON TABLE public.group_plans TO anon, authenticated, postgres, service_role;
GRANT ALL ON TABLE public.group_plan_members TO anon, authenticated, postgres, service_role;
GRANT ALL ON TABLE public.group_tasks TO anon, authenticated, postgres, service_role;

