/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#0a0a0a",
        "on-primary": "#ffffff",
        "brand-green": "#00d4a4",
        "brand-green-deep": "#00b48a",
        "brand-green-soft": "#7cebcb",
        "brand-tag": "#3772cf",
        "brand-warn": "#c37d0d",
        "brand-annotate": "#1ba673",
        "brand-error": "#d45656",
        "brand-cursor": "#888888",
        "hero-sky-from": "#87a8c8",
        "hero-sky-to": "#f5e9d8",
        "hero-dark-from": "#1a3d4a",
        "hero-dark-to": "#2d5a4f",
        "testimonial-orange": "#f55a3c",
        "testimonial-orange-deep": "#cc3a1f",
        canvas: "#ffffff",
        "canvas-dark": "#0a0a0a",
        surface: "#f7f7f7",
        "surface-soft": "#fafafa",
        "surface-code": "#1c1c1e",
        hairline: "#e5e5e5",
        "hairline-soft": "#ededed",
        "hairline-dark": "#1f1f1f",
        ink: "#0a0a0a",
        charcoal: "#1c1c1e",
        slate: "#3a3a3c",
        steel: "#5a5a5c",
        stone: "#888888",
        muted: "#a8a8aa",
        "on-dark": "#ffffff",
        "on-dark-muted": "#b3b3b3",
        danger: {
          3: "#fee2e2",
          6: "#fca5a5",
          11: "#991b1b",
        },
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        geist: ['Geist Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
