import * as THREE from "three";
import { WorkTimelinePoint } from "../types";

export const WORK_TIMELINE: WorkTimelinePoint[] = [
  {
    point: new THREE.Vector3(0, 0, 0),
    year: '2006',
    title: 'Thành lập Trường',
    subtitle: 'Theo Quyết định 134/2006/QĐ-TTg.',
    position: 'right',
  },
  {
    point: new THREE.Vector3(-2, -1, -3),
    year: '2007',
    title: 'Đào tạo đặc biệt',
    subtitle: 'Triển khai các chương trình đào tạo đặc biệt và thu hút đội ngũ giảng viên tinh hoa.',
    position: 'left',
  },
  {
    point: new THREE.Vector3(-3, -3, -6),
    year: '2008',
    title: 'Khởi công xây dựng',
    subtitle: 'Khởi công xây dựng các hạng mục công trình trọng điểm tại cơ sở Thủ Đức.',
    position: 'left',
  },
  {
    point: new THREE.Vector3(-1, -4, -9),
    year: '2009',
    title: 'Nghiên cứu khoa học',
    subtitle: 'Đẩy mạnh nghiên cứu khoa học và công bố quốc tế.',
    position: 'right',
  },
  {
    point: new THREE.Vector3(1, -3, -12),
    year: '2010',
    title: 'Lễ tốt nghiệp đầu tiên',
    subtitle: 'Khẳng định năng lực đào tạo thực tế.',
    position: 'right',
  },
  {
    point: new THREE.Vector3(3, -1, -15),
    year: '2011',
    title: 'Đầu tư trang thiết bị',
    subtitle: 'Tăng cường đầu tư hệ thống phòng máy tính và trang thiết bị hiện đại.',
    position: 'left',
  },
  {
    point: new THREE.Vector3(2, 1, -18),
    year: '2012',
    title: 'Hợp tác quốc tế',
    subtitle: 'Mở rộng hợp tác quốc tế với nhiều tập đoàn công nghệ toàn cầu.',
    position: 'left',
  },
  {
    point: new THREE.Vector3(0, 2, -21),
    year: '2013',
    title: 'Thi đua xuất sắc',
    subtitle: 'Đạt các danh hiệu thi đua xuất sắc trong hệ thống ĐHQG-HCM.',
    position: 'right',
  },
  {
    point: new THREE.Vector3(-2, 1, -24),
    year: '2014',
    title: 'Huân chương Lao động',
    subtitle: 'ĐHQG-HCM nhận Huân chương Lao động hạng Ba.',
    position: 'left',
  },
  {
    point: new THREE.Vector3(-3, -1, -27),
    year: '2015',
    title: 'Kiểm định chất lượng',
    subtitle: 'Hoàn thành kiểm định chất lượng nội bộ theo tiêu chuẩn ĐHQG-HCM.',
    position: 'left',
  },
  {
    point: new THREE.Vector3(-2, -3, -30),
    year: '2016',
    title: 'Kỷ niệm 10 năm',
    subtitle: 'Nhận Huân chương Lao động hạng III.',
    position: 'right',
  },
  {
    point: new THREE.Vector3(0, -4, -33),
    year: '2017',
    title: 'Chuẩn kiểm định',
    subtitle: 'Đạt chuẩn kiểm định chất lượng cơ sở giáo dục chu kỳ 1.',
    position: 'right',
  },
  {
    point: new THREE.Vector3(2, -3, -36),
    year: '2018',
    title: 'Chuẩn AUN-QA',
    subtitle: 'Các chương trình Hệ thống Thông tin, Khoa học Máy tính đạt chuẩn AUN-QA.',
    position: 'left',
  },
  {
    point: new THREE.Vector3(3, -1, -39),
    year: '2019',
    title: 'Mở rộng AUN-QA',
    subtitle: 'Các chương trình Kỹ thuật Phần mềm, Mạng máy tính & Truyền thông, Kỹ thuật Máy tính đạt chuẩn AUN-QA.',
    position: 'left',
  },
  {
    point: new THREE.Vector3(2, 1, -42),
    year: '2020',
    title: 'Anh hùng Lao động',
    subtitle: 'ĐHQG-HCM nhận danh hiệu Anh hùng Lao động thời kỳ đổi mới.',
    position: 'right',
  },
  {
    point: new THREE.Vector3(0, 2, -45),
    year: '2021',
    title: 'Kỷ niệm 15 năm',
    subtitle: 'Ban hành Chiến lược phát triển 2021-2030, tầm nhìn 2045.',
    position: 'right',
  },
  {
    point: new THREE.Vector3(-2, 1, -48),
    year: '2022',
    title: 'An toàn Thông tin',
    subtitle: 'Ngành An toàn Thông tin đạt chuẩn AUN-QA lần thứ 287.',
    position: 'left',
  },
  {
    point: new THREE.Vector3(-3, -1, -51),
    year: '2023',
    title: 'Kiểm định chu kỳ 2',
    subtitle: 'Hoàn thành kiểm định chất lượng cơ sở giáo dục chu kỳ 2 theo tiêu chuẩn mới.',
    position: 'left',
  },
  {
    point: new THREE.Vector3(-2, -3, -54),
    year: '2024',
    title: 'Huân chương hạng Nhất',
    subtitle: 'ĐHQG-HCM nhận Huân chương Lao động hạng Nhất.',
    position: 'right',
  },
  {
    point: new THREE.Vector3(0, -4, -57),
    year: '2025',
    title: 'Nhân lực STEAM',
    subtitle: 'Tham gia đề án đào tạo nhân lực STEAM và chuẩn bị cho Cách mạng Công nghệ mới.',
    position: 'right',
  },
  {
    point: new THREE.Vector3(2, -3, -60),
    year: '2026',
    title: 'Thành tích quốc tế',
    subtitle: 'Huy chương Đồng ICPC Asia Pacific và Giải Nhất quốc tế CTI.',
    position: 'left',
  },
]