-- ============================================================
-- DevOrbit Complete Database Schema
-- Covers all 5 features:
--   1. Subject Orbit (courses + external resources)
--   2. Legacy Repo Finder (github repos, candidates, tech stacks)
--   3. Learning Roadmap (markdown plans with phased items)
--   4. Knowledge Graph (course prerequisite relationships)
--   5. Split-view Note Editor (notes + code snippets)
-- ============================================================

-- ============================================================

-- ============================================================
-- 0. CLEANUP (Ensures schema updates apply)
-- ============================================================
DROP TABLE IF EXISTS course_relationships CASCADE;
DROP TABLE IF EXISTS course_tutorials CASCADE;
DROP TABLE IF EXISTS course_articles CASCADE;
DROP TABLE IF EXISTS course_youtube_playlists CASCADE;
DROP TABLE IF EXISTS repo_candidates CASCADE;
DROP TABLE IF EXISTS repo_tech_stacks CASCADE;
DROP TABLE IF EXISTS github_repos CASCADE;
DROP TABLE IF EXISTS tech_stacks CASCADE;
DROP TABLE IF EXISTS otps CASCADE;
DROP TABLE IF EXISTS roadmap_items CASCADE;
DROP TABLE IF EXISTS roadmap_phases CASCADE;
DROP TABLE IF EXISTS learning_roadmaps CASCADE;
DROP TABLE IF EXISTS notes CASCADE;
DROP TABLE IF EXISTS note_code_snippets CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS student_users CASCADE;
DROP TABLE IF EXISTS admin_users CASCADE;

-- ============================================================
-- 1. USERS & AUTH
-- ============================================================
create table if not exists admin_users (
    id            bigint generated by default as identity primary key,
    username      varchar(255) not null unique,
    password_hash varchar(255) not null,
    active        boolean      not null default true
);

create table if not exists student_users (
    id            bigint generated by default as identity primary key,
    student_code  varchar(255) not null unique,
    full_name     varchar(255) not null,
    email         varchar(255) not null unique,
    password_hash varchar(255) not null,
    active        boolean      not null default true
);

create table if not exists student_bookmarks (
    id          bigint generated by default as identity primary key,
    student_id   bigint       not null references student_users(id) on delete cascade,
    target_type varchar(20)  not null,
    target_id   bigint       not null,
    title       varchar(255) not null,
    subtitle    varchar(255),
    url         varchar(255) not null,
    created_at  timestamp    not null default now(),
    unique (student_id, target_type, target_id)
);

create table if not exists otps (
    id          bigint generated by default as identity primary key,
    email       varchar(255) not null,
    otp_code    varchar(6)   not null,
    expires_at  timestamp    not null,
    created_at  timestamp    not null default now()
);

-- ============================================================
-- 6. PHOTOBOOTH — custom frame definitions
-- ============================================================
create table if not exists photobooth_frames (
    id                 uuid        default gen_random_uuid() primary key,
    frame_id           text        not null unique,
    name               text        not null,
    display_name       text        not null,
    photo_count        integer     not null check (photo_count in (1, 2, 3, 4, 6)),
    description        text        default '',
    slots              jsonb       not null default '[]'::jsonb,
    overlay_image_url  text,
    filter             text        default 'normal',
    background_color   text        default '#ffffff',
    created_at         timestamp   not null default now(),
    updated_at         timestamp   not null default now()
);


-- ============================================================
-- 2. SUBJECT ORBIT — Courses
-- ============================================================
create table if not exists courses (
    stt        bigint generated by default as identity primary key,
    mamh       varchar(20)  not null unique,
    tenmh        varchar(255) not null,
    tenmh_en     varchar(255),
    sotc         integer      not null default 0,
    lt           integer      not null default 0,
    th           integer      not null default 0,
    loaimonhoc   varchar(50)  not null,
    semester     integer,
    is_open      boolean      not null default true,
    management_unit varchar(100),
    description  text,
    mamh_old     varchar(50),
    equivalent_mh text,
    prerequisite_mh text,
    previous_mh  text
);

-- External learning resources linked to each course
create table if not exists course_youtube_playlists (
    id          bigint generated by default as identity primary key,
    course_id   bigint       not null references courses(stt) on delete cascade,
    title       varchar(255) not null,
    url         varchar(255) not null,
    description text,
    channel_name varchar(255),
    created_at  timestamp    not null default now()
);

create table if not exists course_articles (
    id          bigint generated by default as identity primary key,
    course_id   bigint       not null references courses(stt) on delete cascade,
    title       varchar(255) not null,
    url         varchar(255) not null,
    author      varchar(255),
    description text,
    created_at  timestamp    not null default now()
);

create table if not exists course_tutorials (
    id          bigint generated by default as identity primary key,
    course_id   bigint       not null references courses(stt) on delete cascade,
    title       varchar(255) not null,
    url         varchar(255) not null,
    type        varchar(50)  not null default 'article',
    description text,
    created_at  timestamp    not null default now()
);

-- ============================================================
-- 3. LEGACY REPO FINDER — GitHub repos & tech stacks
-- ============================================================
create table if not exists tech_stacks (
    id      bigint generated by default as identity primary key,
    name    varchar(120) not null,
    repo_id bigint       -- legacy column; new code uses join table
);

create unique index if not exists uk_tech_stack_name on tech_stacks (name);

create table if not exists github_repos (
    id               bigint generated by default as identity primary key,
    repo_name        varchar(255)  not null,
    description      text,
    github_url       varchar(255)  not null,
    tech_stack       varchar(255),
    subject_id       varchar(20),
    display_name     varchar(255),
    primary_language varchar(100),
    is_active        boolean       not null default true,
    course_id        bigint        references courses(stt),
    stars            integer
);

create table if not exists repo_tech_stacks (
    repo_id       bigint not null references github_repos(id) on delete cascade,
    tech_stack_id bigint not null references tech_stacks(id) on delete cascade,
    primary key (repo_id, tech_stack_id)
);

DROP TYPE IF EXISTS repo_candidate_status CASCADE;
CREATE TYPE repo_candidate_status AS ENUM (
    'NEW', 'APPROVED', 'REJECTED'
);

DROP TYPE IF EXISTS roadmap_item_target_type CASCADE;
CREATE TYPE roadmap_item_target_type AS ENUM (
    'COURSE', 'REPO'
);

create table if not exists repo_candidates (
    id               bigint generated by default as identity primary key,
    course_id        bigint                 references courses(stt),
    scan_query       varchar(255),
    github_owner     varchar(255),
    github_name      varchar(255),
    github_url       varchar(255) not null,
    description      text,
    primary_language varchar(100),
    topics           text,
    stars            integer,
    forks            integer,
    last_pushed_at   varchar(255),
    readme_excerpt   text,
    status           varchar(20) not null default 'NEW',
    review_note      text,
    assigned_reviewer varchar(50)
);

create table if not exists learning_roadmaps (
    id               bigint generated by default as identity primary key,
    student_id       bigint       not null references student_users(id) on delete cascade,
    title            varchar(255) not null,
    description      text,
    markdown_content text,
    is_public        boolean      not null default false,
    created_at       timestamp    not null default now(),
    updated_at       timestamp    not null default now()
);

create table if not exists roadmap_phases (
    id          bigint generated by default as identity primary key,
    roadmap_id  bigint       not null references learning_roadmaps(id) on delete cascade,
    title       varchar(255) not null,
    description text,
    sort_order  integer      not null default 0,
    created_at  timestamp    not null default now()
);

create table if not exists roadmap_items (
    id          bigint generated by default as identity primary key,
    phase_id    bigint                    not null references roadmap_phases(id) on delete cascade,
    target_type roadmap_item_target_type  not null,
    target_id   bigint                    not null,
    title       varchar(255),
    note        text,
    sort_order  integer                   not null default 0,
    created_at  timestamp                 not null default now()
);

DROP TYPE IF EXISTS course_relation_type CASCADE;
CREATE TYPE course_relation_type AS ENUM (
    'PREREQUISITE',
    'COMPLEMENTARY',
    'COREQUISITE'
);

DROP TYPE IF EXISTS note_target_type CASCADE;
CREATE TYPE note_target_type AS ENUM (
    'COURSE', 'REPO', 'NONE'
);

create table if not exists course_relationships (
    id              bigint                 generated by default as identity primary key,
    course_id       bigint                 not null references courses(stt) on delete cascade,
    related_course_id bigint               not null references courses(stt) on delete cascade,
    relation_type   course_relation_type   not null,
    created_at      timestamp              not null default now(),
    unique (course_id, related_course_id),
    check (course_id <> related_course_id)
);

-- ============================================================
-- 7. SPLIT-VIEW NOTE EDITOR — Notes & code snippets
-- ============================================================
DROP TYPE IF EXISTS note_target_type CASCADE;
CREATE TYPE note_target_type AS ENUM (
    'COURSE', 'REPO', 'NONE'
);

create table if not exists notes (
    id              bigint generated by default as identity primary key,
    student_id      bigint            not null references student_users(id) on delete cascade,
    title           varchar(255)      not null,
    content_markdown text,
    target_type     note_target_type  not null default 'NONE',
    target_id       bigint,
    created_at      timestamp         not null default now(),
    updated_at      timestamp         not null default now()
);

create table if not exists note_code_snippets (
    id         bigint generated by default as identity primary key,
    note_id    bigint       not null references notes(id) on delete cascade,
    language   varchar(50)  not null,
    code       text         not null,
    caption    varchar(255),
    sort_order integer      not null default 0
);

-- ============================================================
-- INDEXES for performance
-- ============================================================
create index if not exists idx_github_repos_course     on github_repos(course_id);
create index if not exists idx_github_repos_active     on github_repos(is_active);
create index if not exists idx_repo_candidates_status  on repo_candidates(status);
create index if not exists idx_roadmaps_student        on learning_roadmaps(student_id);
create index if not exists idx_roadmap_phases_roadmap  on roadmap_phases(roadmap_id);
create index if not exists idx_roadmap_items_phase     on roadmap_items(phase_id);
create index if not exists idx_course_rels_course      on course_relationships(course_id);
create index if not exists idx_notes_student           on notes(student_id);
create index if not exists idx_notes_target            on notes(target_type, target_id);
create index if not exists idx_note_snippets_note      on note_code_snippets(note_id);
create index if not exists idx_course_yt_course        on course_youtube_playlists(course_id);
create index if not exists idx_course_articles_course  on course_articles(course_id);
create index if not exists idx_course_tutorials_course on course_tutorials(course_id);

-- ============================================================
-- SEED DATA
-- ============================================================
insert into admin_users (username, password_hash, active)
values ('admin', '$2b$12$3IpxxJtwI/zV8hYwQc8W9eWRkf.l0yocc3Di5FvA65J0QiJ395WSe', true)
on conflict (username) do nothing;

insert into courses (mamh, tenmh, sotc, lt, th, loaimonhoc)
values
('SS003', 'Tư tưởng Hồ Chí Minh', 2, 2, 0, 'DAI_CUONG'),
('SS007', 'Triết học Mác – Lênin', 3, 3, 0, 'DAI_CUONG'),
('SS008', 'Kinh tế chính trị Mác – Lênin', 2, 2, 0, 'DAI_CUONG'),
('SS009', 'Chủ nghĩa xã hội khoa học', 2, 2, 0, 'DAI_CUONG'),
('SS010', 'Lịch sử Đảng Cộng sản Việt Nam', 2, 2, 0, 'DAI_CUONG'),
('SS006', 'Pháp luật đại cương', 2, 2, 0, 'DAI_CUONG'),
('MA006', 'Giải tích', 4, 4, 0, 'DAI_CUONG'),
('MA003', 'Đại số tuyến tính', 3, 3, 0, 'DAI_CUONG'),
('MA004', 'Cấu trúc rời rạc', 4, 4, 0, 'DAI_CUONG'),
('MA005', 'Xác suất thống kê', 3, 3, 0, 'DAI_CUONG'),
('IT001', 'Nhập môn Lập trình', 4, 3, 1, 'BAT_BUOC'),
('ENG01', 'Anh văn 1', 4, 4, 0, 'DAI_CUONG'),
('ENG02', 'Anh văn 2', 4, 4, 0, 'DAI_CUONG'),
('ENG03', 'Anh văn 3', 4, 4, 0, 'DAI_CUONG'),
('SE005', 'Giới thiệu ngành Kỹ thuật Phần mềm', 1, 1, 0, 'BAT_BUOC'),
('IT002', 'Lập trình hướng đối tượng', 4, 3, 1, 'BAT_BUOC'),
('IT003', 'Cấu trúc dữ liệu và giải thuật', 4, 3, 1, 'BAT_BUOC'),
('IT004', 'Cơ sở dữ liệu', 4, 3, 1, 'BAT_BUOC'),
('IT005', 'Nhập môn mạng máy tính', 4, 3, 1, 'BAT_BUOC'),
('IT007', 'Hệ điều hành', 4, 3, 1, 'BAT_BUOC'),
('IT012', 'Tổ chức và cấu trúc máy tính II', 4, 3, 1, 'BAT_BUOC'),
('IT008', 'Lập trình trực quan', 4, 3, 1, 'BAT_BUOC'),
('SE100', 'Phương pháp phát triển phần mềm hướng đối tượng', 4, 3, 1, 'BAT_BUOC'),
('SE104', 'Nhập môn Công nghệ phần mềm', 4, 3, 1, 'BAT_BUOC'),
('SE101', 'Phương pháp mô hình hóa', 3, 3, 0, 'TU_CHON'),
('SE102', 'Nhập môn phát triển game', 3, 2, 1, 'TU_CHON'),
('SE114', 'Nhập môn ứng dụng di động', 3, 2, 1, 'TU_CHON'),
('SE106', 'Đặc tả hình thức', 4, 4, 0, 'TU_CHON'),
('SE214', 'Công nghệ phần mềm chuyên sâu', 4, 3, 1, 'TU_CHON'),
('SE301', 'Phát triển phần mềm mã nguồn mở', 3, 3, 0, 'TU_CHON'),
('SE215', 'Giao tiếp người máy', 4, 3, 1, 'TU_CHON'),
('SE113', 'Kiểm chứng phần mềm', 4, 3, 1, 'TU_CHON'),
('SE358', 'Quản lý dự án phát triển phần mềm', 4, 3, 1, 'TU_CHON'),
('SE330', 'Ngôn ngữ lập trình Java', 4, 3, 1, 'TU_CHON'),
('SE332', 'Chuyên đề CSDL nâng cao', 2, 2, 0, 'TU_CHON'),
('SE334', 'Các phương pháp lập trình', 3, 2, 1, 'TU_CHON'),
('SE347', 'Công nghệ Web và ứng dụng', 4, 3, 1, 'TU_CHON'),
('SE350', 'Chuyên đề E-learning', 2, 2, 0, 'TU_CHON'),
('SE351', 'Xử lý song song', 4, 3, 1, 'TU_CHON'),
('SE343', 'Công nghệ Portal', 3, 3, 0, 'TU_CHON'),
('SE355', 'Máy học và các công cụ', 3, 2, 1, 'TU_CHON'),
('SE310', 'Công nghệ .NET', 4, 3, 1, 'TU_CHON'),
('SE346', 'Lập trình trên thiết bị di động', 4, 3, 1, 'TU_CHON'),
('SE404', 'Chuyên đề E-Government', 2, 2, 0, 'TU_CHON'),
('SE331', 'Chuyên đề E-Commerce', 2, 2, 0, 'TU_CHON'),
('SE313', 'Một số thuật toán thông minh', 2, 2, 0, 'TU_CHON'),
('SE352', 'Phát triển ứng dụng VR', 3, 2, 1, 'TU_CHON'),
('SE109', 'Phát triển, vận hành, bảo trì phần mềm', 3, 3, 0, 'TU_CHON'),
('SE356', 'Kiến trúc phần mềm', 4, 3, 1, 'TU_CHON'),
('SE357', 'Kỹ thuật phân tích yêu cầu', 3, 2, 1, 'TU_CHON'),
('SE325', 'Chuyên đề J2EE', 4, 3, 1, 'TU_CHON'),
('SE221', 'Lập trình game nâng cao', 4, 3, 1, 'TU_CHON'),
('SE220', 'Thiết kế game', 3, 3, 0, 'TU_CHON'),
('SE320', 'Lập trình đồ họa 3 chiều với Direct 3D', 4, 3, 1, 'TU_CHON'),
('SE327', 'Phát triển và vận hành game', 3, 3, 0, 'TU_CHON'),
('SE328', 'Lập trình TTNT trong game', 4, 3, 1, 'TU_CHON'),
('SE344', 'Lập trình game trên các thiết bị di động', 4, 3, 1, 'TU_CHON'),
('SE329', 'Thiết kế 3D game engine', 4, 3, 1, 'TU_CHON'),
('SE501', 'Thực tập doanh nghiệp', 2, 2, 0, 'TOT_NGHIEP'),
('SE121', 'Đồ án 1', 2, 2, 0, 'BAT_BUOC'),
('SE122', 'Đồ án 2', 2, 2, 0, 'BAT_BUOC'),
('SE505', 'Khóa luận tốt nghiệp', 10, 10, 0, 'TOT_NGHIEP'),
('SE506', 'Đồ án tốt nghiệp tại doanh nghiệp', 10, 10, 0, 'TOT_NGHIEP'),
('SE507', 'Đồ án tốt nghiệp', 6, 6, 0, 'TOT_NGHIEP'),
('SE400', 'Seminar các vấn đề hiện đại của Công nghệ Phần mềm', 4, 4, 0, 'TU_CHON'),
('SE406', 'Mẫu thiết kế hướng đối tượng', 4, 4, 0, 'TU_CHON'),
('SE403', 'Nguyên lý thiết kế thế giới ảo', 4, 4, 0, 'TU_CHON'),
('SE407', 'Chuyên đề Pervasive and Mobile Computing', 4, 4, 0, 'TU_CHON'),
('SS004', 'Kỹ năng nghề nghiệp', 2, 2, 0, 'TU_CHON')
on conflict (mamh) do nothing;
