package vn.edu.uit.devorbit_api.dto.admin;

import java.time.LocalDateTime;

/**
 * Response DTO for a course article resource.
 *
 * <p>This record represents a learning article linked to a course.
 * It is returned when listing, creating, or updating articles. Every
 * article has an auto-generated {@code id}, the owning course's
 * {@code courseId}, and a {@code createdAt} timestamp set by the server.</p>
 *
 * <p><b>Used by:</b><ul>
 *   <li>{@code GET /api/admin/courses/{courseId}/resources/articles}
 *       — list all articles for a course.</li>
 *   <li>{@code POST /api/admin/courses/{courseId}/resources/articles}
 *       — create a new article (returns the persisted entity).</li>
 *   <li>{@code PUT /api/admin/courses/{courseId}/resources/articles/{id}}
 *       — update an article (returns updated entity).</li>
 * </ul></p>
 *
 * @param id          Internal primary key (auto-generated by the database).
 * @param courseId    ID of the course this article belongs to.
 * @param title       Article headline.
 *                    Example: {@code "Understanding Java Streams"}.
 * @param url         Full URL to the article.
 *                    Example: {@code "https://example.com/java-streams-guide"}.
 * @param author      Name of the article's author (may be {@code null}).
 *                    Example: {@code "John Doe"}.
 * @param description Short summary or excerpt of the article (may be {@code null}).
 * @param createdAt   Timestamp when the article was first persisted (set by the server).
 */
public record ArticleResponse(
    Long id,
    Long courseId,
    String title,
    String url,
    String author,
    String description,
    LocalDateTime createdAt
) {}
