package vn.edu.uit.devorbit_api.dto.admin;

import java.time.LocalDateTime;

/**
 * Response DTO for a course tutorial resource.
 *
 * <p>This record represents a tutorial linked to a course. It mirrors
 * the fields from {@link TutorialRequest} plus the server-generated
 * {@code id}, {@code courseId}, and {@code createdAt} timestamp.</p>
 *
 * <p><b>Used by:</b><ul>
 *   <li>{@code GET /api/admin/courses/{courseId}/resources/tutorials}
 *       — list all tutorials for a course.</li>
 *   <li>{@code POST /api/admin/courses/{courseId}/resources/tutorials}
 *       — create a new tutorial (returns the persisted entity).</li>
 *   <li>{@code PUT /api/admin/courses/{courseId}/resources/tutorials/{id}}
 *       — update a tutorial (returns the updated entity).</li>
 * </ul></p>
 *
 * @param id          Internal primary key (auto-generated by the database).
 * @param courseId    ID of the course this tutorial belongs to.
 * @param title       Tutorial title.
 *                    Example: {@code "Spring Boot Tutorial for Beginners"}.
 * @param url         Full URL to the tutorial.
 *                    Example: {@code "https://example.com/spring-boot-intro"}.
 * @param type        Tutorial format/category (may be {@code null}).
 *                    Examples: {@code "video"}, {@code "interactive"}, {@code "text"}.
 * @param description Short summary of the tutorial (may be {@code null}).
 * @param createdAt   Timestamp when the tutorial was first persisted (set by the server).
 */
public record TutorialResponse(
    Long id,
    Long courseId,
    String title,
    String url,
    String type,
    String description,
    LocalDateTime createdAt
) {}
