package vn.edu.uit.devorbit_api.dto.admin;

import java.time.LocalDateTime;

/**
 * Response DTO for a YouTube playlist resource linked to a course.
 *
 * <p>This record represents a YouTube playlist that has been curated
 * as a learning resource for a specific course. It contains all fields
 * from {@link YoutubePlaylistRequest} plus the server-generated
 * {@code id}, {@code courseId}, and {@code createdAt} timestamp.</p>
 *
 * <p><b>Used by:</b><ul>
 *   <li>{@code GET /api/admin/courses/{courseId}/resources/youtube-playlists}
 *       — list all YouTube playlists for a course.</li>
 *   <li>{@code POST /api/admin/courses/{courseId}/resources/youtube-playlists}
 *       — create a new playlist (returns the persisted entity).</li>
 *   <li>{@code PUT /api/admin/courses/{courseId}/resources/youtube-playlists/{id}}
 *       — update a playlist (returns the updated entity).</li>
 * </ul></p>
 *
 * @param id          Internal primary key (auto-generated by the database).
 * @param courseId    ID of the course this playlist belongs to.
 * @param title       Playlist title (e.g. {@code "Java Programming Full Course"}).
 * @param url         Full YouTube playlist URL.
 *                    Example: {@code "https://www.youtube.com/playlist?list=PLA0cL0YhG8"}.
 * @param description Optional summary of the playlist content (may be {@code null}).
 * @param channelName Optional name of the YouTube channel (may be {@code null}).
 *                    Example: {@code "Programming with Mosh"}.
 * @param createdAt   Timestamp when the playlist entry was first persisted (set by the server).
 */
public record YoutubePlaylistResponse(
    Long id,
    Long courseId,
    String title,
    String url,
    String description,
    String channelName,
    LocalDateTime createdAt
) {}
