package vn.edu.uit.devorbit_api.dto.publicapi;

import jakarta.validation.constraints.NotBlank;
import java.util.UUID;

/**
 * SUBJECT QA REQUEST = a student's question for the AI tutor.
 *
 * POST /api/ai/subject-qa/query
 * POST /api/ai/subject-qa/stream
 *
 * @NotBlank on message ensures the question isn't empty.
 * sessionId is optional (null = start a new conversation;
 * provided = continue existing conversation for context).
 * The session ID is generated by the server when a new session starts
 * and returned in the response for the client to store.
 */
public record SubjectQaRequest(
    @NotBlank String message,  // The student's question (required)
    UUID sessionId              // Existing session UUID (null = new session)
) {}
