-- Migration: Create community_presences table
-- Date: 2026-06-17 22:18:00

CREATE TABLE IF NOT EXISTS public.community_presences (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id character varying(255) NOT NULL,
    subscription_id character varying(255) NOT NULL,
    channel_id bigint NOT NULL,
    student_code character varying(255) NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_community_presences_channel FOREIGN KEY (channel_id) REFERENCES public.chat_channels(id) ON DELETE CASCADE,
    CONSTRAINT fk_community_presences_student FOREIGN KEY (student_code) REFERENCES public.student_users(student_code) ON DELETE CASCADE
);

ALTER TABLE public.community_presences ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Deny direct API access" ON public.community_presences 
    TO anon, authenticated USING (false) WITH CHECK (false);

GRANT ALL ON TABLE public.community_presences TO postgres, service_role;
