package vn.edu.uit.devorbit_api.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * CHAT SESSION = a conversation thread between a student and the AI tutor.
 *
 * Maps to the "chat_sessions" table.
 * Each session groups multiple ChatMessages into one Q&A thread.
 *
 * How it works:
 *   1. Student starts a session with a question
 *   2. All follow-up questions on the same topic go in the same session
 *   3. The AI uses the session's message history for context
 *
 * The title is auto-generated by AI (e.g., "Understanding OOP Concepts")
 * to help students identify their past conversations.
 *
 * Sessions can be anonymous (student = null) for unauthenticated users.
 *
 * UUID primary key: harder to guess compared to auto-increment IDs.
 */
@Entity
@Table(name = "chat_sessions")
@Getter @Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ChatSession {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * The student who owns this session.
     * Nullable = anonymous users can also chat (but can't resume later).
     * @NotFound(IGNORE) = if student is deleted, keep the session.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @NotFound(action = NotFoundAction.IGNORE)
    @JoinColumn(name = "student_id")
    private StudentUser student;

    /**
     * Auto-generated title summarizing the conversation.
     * Example: "Java Collections Framework Questions"
     */
    @Column(nullable = false)
    private String title;

    @Column(name = "created_at", nullable = false, updatable = false)
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();

    @Column(name = "updated_at", nullable = false)
    @Builder.Default
    private LocalDateTime updatedAt = LocalDateTime.now();

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
